/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0003
 * Generated: 9/2/2026 12:10:03 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#1
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#2
	CloseBoard 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#2
	ShowBoard 2
	LocalScript
End

Script 2:
	Call Function#3
	LocalScript
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckTrainerCardLevel 0x800C
	CompareVarValue 0x800C 4
	JumpIf GREATER/EQUAL Function#4
	SetVar 0x8004 0
	GetTimePeriod 0x800C
	DummyGetVar 0x800C
	SetVar 0x8004 83
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	SetVar 0x8004 84
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	SetVar 0x8004 0
	MessageFlex 0x8004
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
End

Script 4:
	MecScript
	LockAll
	GetPartyCount 0x8004
	SetVar 0x8005 0
	SurvivePoison 0x800C 0x8005
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	TextPokeNickname 0 0x8005
	Message 53
	IncrementVar 0x8005 1
	CompareVars 0x8004 0x8005
	JumpIf DIFFERENT Function#9
	CountAlivePokemonExceptFirst 0x800C 6
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CloseMessage
	ReleaseAll
End

Script 5:
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitButton
	FadeScreen 6 1 0 0
	WaitFadeScreen
End

Script 6:
	ClearFlag 32
	Call Function#11
	ReturnScriptWkSet 0x800C
	CloseMessage
End

Script 7:
	SetFlag 32
	Call Function#11
	SetVarFromVariable 0x4000 0x800C
	LocalScript
End

Script 8:
	Call Function#12
	Message 32
	WaitButton
	LocalScript
End

Script 9:
	Call Function#13
	LocalScript
End

Script 10:
	Call Function#14
	LocalScript
End

Script 11:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_PC_ON
	Call Function#15
	TextPlayerName 0
	Message 33
	OpenTouchScreen
Jump Function#16

Script 12:
	Message 38
	LocalScript
End

Script 13:
	MecScript
	LockAll
	Movement Player Action#1
	Movement Overworld.0 Action#2
	WaitMovement
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPlayerName 0
	Message 41
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	PlaySound SEQ_ME_ASA
	WaitSound
	HealPokemon
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 42
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 14:
	MecScript
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#17
	SetPlayerForm 2048
Jump Function#18

Script 15:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SealCapsuleScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FadeScreen 6 1 0 0
	WaitFadeScreen
	GeonetScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CMD_455
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 54
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 57
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 20:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 58
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 21:
	CheckItem ITEM_BIKE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#19
	MecScript
	LockAll
	PlayFanfare SEQ_SE_CONFIRM
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#20
	Message 59
	YesNoBox 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#21
	RideBike 1
	CloseMessage
	ReleaseAll
End

Script 22:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 62
	WaitButton
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	EggHatchScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 23:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 65
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 24:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 103
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 112 255 0
	CreateMultiTouchBox 113 255 1
	CreateMultiTouchBox 114 255 2
	CreateMultiTouchBox 115 255 3
	CreateMultiTouchBox 116 255 4
	CloseMultiTouch
	CompareVarValue 0x800C 4
	JumpIf GREATER/EQUAL Function#22
	SetVar 0x8004 104
	IncrementVar 0x8004 0x800C
	MessageFlex 0x8004
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	SetVar 0x8000 2
	IncrementVar 0x8000 0x800C
	CMD_492 0x8000 0x800C 0x8001
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#22
	Message 109
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	CompareVarValue 0x8001 0xFFFF
	JumpIf EQUAL Function#24
	CMD_494 0 0x8001
	Message 111
Jump Function#25

Script 25:
	Message 20
	WaitButton
	CloseMessage
End

Script 26:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 68
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 27:
	Call Function#26
	Message 32
	WaitButton
	LocalScript
End

Script 28:
End

Script 29:
	MecScript
	LockAll
	ReleaseAll
End

Script 30:
	StopMusic 0
	CheckPlayerGender 0x800C
	CompareVarValue 0x800C 0
	CallIf EQUAL Function#27
	CompareVarValue 0x800C 1
	CallIf EQUAL Function#28
	LocalScript
End

Script 31:
	FadeOutMusic 0 30
	StopMusic 0
	PlayDefaultMusic
	LocalScript
End

Script 32:
	StopMusic 0
	TempMusic SEQ_GS_E_RIVAL1
	LocalScript
End

Script 33:
	UseScript_#31

Script 34:
	Call Function#29
	LocalScript
End

Script 35:
	Call Function#26
	Message 90
	LocalScript
End

Script 36:
	Call Function#12
	Message 90
	LocalScript
End

Script 37:
	StopMusic 0
	TempMusic SEQ_GS_E_TSURETEKE1
	LocalScript
End

Script 38:
	StopMusic 0
	TempMusic SEQ_GS_E_TSURETEKE2
	LocalScript
End

Script 39:
	UseScript_#31

Script 40:
	PreparePokeGearCall 0x8004 0x8005 0x8006
	Call Function#30
	LocalScript
End

Script 41:
	CheckFlag 253
	JumpIf EQUAL Function#31
	CompareVarValue 0x404E 4
	JumpIf DIFFERENT Function#31
	CompareVarValue 0x404F 4
	JumpIf DIFFERENT Function#31
	CompareVarValue 0x4050 4
	JumpIf DIFFERENT Function#31
	CompareVarValue 0x4051 4
	JumpIf DIFFERENT Function#31
	CompareVarValue 0x404D 4
	JumpIf DIFFERENT Function#31
	SetFlag 253
	CMD_680 31
Jump Function#31

Script 42:
	Message 93
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Script 43:
	StopMusic 0
	TempMusic SEQ_GS_E_MINAKI
	LocalScript
End

Script 44:
	UseScript_#31

Script 45:
	StopMusic 0
	TempMusic SEQ_GS_IBUKI
	LocalScript
End

Script 46:
	UseScript_#31

Script 47:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	InitWFC 0x800C
	SetVarFromVariable 0x8004 0x800C
	CMD_662 0x8005 0x8004 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	LocalScript
End

Script 48:
	Call Function#30
End

Script 49:
Jump Function#33

Script 50:
	MartScreen 0x8004
Jump Function#34

Script 51:
	MartSell
Jump Function#34

Script 52:
	CloseTouchScreen
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 1
	WaitButton
	CloseMessage
	LocalScript
End

Script 53:
Jump Function#35

Script 54:
	SpMartScreen 0x8004
Jump Function#36

Script 55:
	MartSell
Jump Function#36

Script 56:
	CloseTouchScreen
	CheckFlag 367
	JumpIf EQUAL Function#37
	CheckFlag 368
	JumpIf EQUAL Function#38
	CheckFlag 369
	JumpIf EQUAL Function#39
	CheckFlag 394
	JumpIf EQUAL Function#40
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 1
	WaitButton
	CloseMessage
	LocalScript
End

Script 57:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 321 255 0
	CreateMultiTouchBox 324 255 1
	CreateMultiTouchBox 323 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#41
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#42
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#43
End

Script 58:
	CMD_771
	LocalScript
End

Script 59:
	CloseTouchScreen
	LocalScript
End

Script 60:
	CloseTouchScreen
	LocalScript
End

Script 61:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 321 255 0
	CreateMultiTouchBox 324 255 1
	CreateMultiTouchBox 323 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#44
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#45
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#46
End

Script 62:
	CMD_772
	LocalScript
End

Script 63:
	CloseTouchScreen
	LocalScript
End

Script 64:
	CloseTouchScreen
	LocalScript
End

Script 65:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	GetFollowingPokePartySlot 0x8005
	TextPokeNickname 0 0x8005
	Message 99
	CloseMessage
	CMD_806
	GetFollowingPokePartySlot 0x8005
	TextPokeNickname 0 0x8005
	Message 100
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 66:
	StopMusic 0
	TempMusic SEQ_GS_E_G_PICHU
	LocalScript
End

Script 67:
	UseScript_#31

Script 68:
	StopMusic 0
	TempMusic SEQ_GS_E_MAIKO_THEME
	LocalScript
End

Script 69:
	UseScript_#31

Script 70:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	FinishOverworldScreen
	PlaySound SEQ_ME_ASA
	WaitSound
	HealPokemon
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	LocalScript
End

Script 71:
	StopMusic 0
	TempMusic SEQ_GS_E_RIVAL2
	LocalScript
End

Script 72:
	UseScript_#31

Script 73:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 118
	YesNoBox 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#47
	DummyTextTrap 0 0x800C
	PlayFanfare SEQ_SE_DP_CARD2
	TextPlayerName 0
	TextItem 1 0x800C
	Message 119
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 74:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8005
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	GetPartyPokemonID 0x8005 0x800C
	CheckHasLearnableMoves 0x800C 0x8005
	FadeScreen 6 1 0 0
	WaitFadeScreen
	RememberMoveScreen 0x8005
	ResponseTeachMove 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 75:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	TextPlayerName 0
	Message 37
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 76:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 120
	CloseMessage
	TrainerBattle TRAINER_VICTORIA_005 TRAINER_NONE 0 0
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	ShowBoard 2
	LocalScript
End

Function 2:
	ShowBoard 4
	WaitBoard
	Menu
	LocalScript
End

Function 3:
	GetItemPocket 0x8004 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 7
	JumpIf EQUAL Function#48
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 6
	JumpIf EQUAL Function#49
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#50
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#51
End

Function 4:
	CheckFlag 100
	JumpIf EQUAL Function#52
	SetFlag 100
	Message 4
	TextPlayerName 0
	Message 5
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#53
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 5:
	MessageFlex 0x8004
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
End

Function 6:
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#54
	SetPlayerForm 2048
Jump Function#55

Function 7:
	Message 3
	WaitButton
	CloseTouchScreen
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 8:
	IncrementVar 0x8005 1
	CompareVars 0x8004 0x8005
	JumpIf DIFFERENT Function#9
	CountAlivePokemonExceptFirst 0x800C 6
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CloseMessage
	ReleaseAll
End

Function 9:
	SurvivePoison 0x800C 0x8005
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#8
	TextPokeNickname 0 0x8005
	Message 53
	IncrementVar 0x8005 1
	CompareVars 0x8004 0x8005
	JumpIf DIFFERENT Function#9
	CountAlivePokemonExceptFirst 0x800C 6
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
	CloseMessage
	ReleaseAll
End

Function 10:
	TextPlayerName 0
	Message 11
	WaitButton
	CloseMessage
	FadeOutMusic 0 10
	FadeScreen 6 1 0 0
	WaitFadeScreen
	FinishOverworldScreen
	DummyLostBattle
End

Function 11:
	ShowSaveBox
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#56
	CheckSaveGame 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#57
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#58
	CompareVarValue 0x800C 2
	JumpIf EQUAL Function#59
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#60
End

Function 12:
	PlaySound SEQ_ME_ACCE
	GiveAccessory 0x8004 0x8005
	TextAccessory 0 0x8004
	Message 25
	WaitSound
	TextPlayerName 0
	TextAccessory 1 0x8004
Return

Function 13:
	Call Function#3
	GiveItem 0x8004 0x8005 0x800C
	GetItemPocket 0x8004 0x800C
	CompareVarValue 0x800C 7
	CallIf EQUAL Function#61
	CompareVarValue 0x800C 7
	CallIf DIFFERENT Function#62
	CompareVarValue 0x8005 1
	JumpIf GREATER Function#63
	Message 30
Jump Function#64

Function 14:
	Message 27
	WaitButton
Return

Function 15:
	CheckFlag 399
	JumpIf EQUAL Function#65
	PreparePCAnimation 90
	OpenPCAnimation 90
	WaitDoor 90
Return

Function 16:
	TextPlayerName 0
	Message 34
	MultiTouchStandardText 1 1 0 1 0x8006
	CheckFlag 2422
	CallIf LESS Function#66
	CheckFlag 2422
	CallIf EQUAL Function#67
	CreateMultiTouchBox 63 255 1
	CheckFlag 2404
	JumpIf EQUAL Function#68
	CheckFlag 2404
	JumpIf LESS Function#69
Jump Function#69

Function 17:
	SetPlayerForm 256
	UpdatePlayerForm
	Movement Player Action#3
	WaitMovement
	Message 44
	Call Function#70
	Call Function#71
	CheckBadge 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#72
	Message 45
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#73
	SetPlayerForm 1024
Jump Function#74

Function 18:
	UpdatePlayerForm
	Movement Player Action#3
	WaitMovement
	Message 44
	Call Function#70
	Call Function#71
	CheckBadge 0 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#72
	Message 45
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#73
	SetPlayerForm 1024
Jump Function#74

Function 19:
End

Function 20:
	Message 60
	YesNoBox 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#21
	RideBike 0
	CloseMessage
	ReleaseAll
End

Function 21:
	CloseMessage
	ReleaseAll
End

Function 22:
	Message 108
Jump Function#25

Function 23:
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 112 255 0
	CreateMultiTouchBox 113 255 1
	CreateMultiTouchBox 114 255 2
	CreateMultiTouchBox 115 255 3
	CreateMultiTouchBox 116 255 4
	CloseMultiTouch
	CompareVarValue 0x800C 4
	JumpIf GREATER/EQUAL Function#22
	SetVar 0x8004 104
	IncrementVar 0x8004 0x800C
	MessageFlex 0x8004
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	SetVar 0x8000 2
	IncrementVar 0x8000 0x800C
	CMD_492 0x8000 0x800C 0x8001
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#22
	Message 109
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	CompareVarValue 0x8001 0xFFFF
	JumpIf EQUAL Function#24
	CMD_494 0 0x8001
	Message 111
Jump Function#25

Function 24:
	Message 110
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 25:
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 26:
	PlaySound SEQ_ME_ACCE
	GiveDressupBackground 0x8004
	TextBackgroundName 0 0x8004
	Message 25
	WaitSound
	TextPlayerName 0
	TextBackgroundName 1 0x8004
Return

Function 27:
	TempMusic SEQ_GS_E_SUPPORT_F
Return

Function 28:
	TempMusic SEQ_GS_E_SUPPORT_M
Return

Function 29:
	Call Function#3
	GiveItem 0x8004 0x8005 0x800C
	GetItemPocket 0x8004 0x800C
	CompareVarValue 0x800C 7
	CallIf EQUAL Function#61
	CompareVarValue 0x800C 7
	CallIf DIFFERENT Function#62
	Message 89
Return

Function 30:
	PlayFanfare SEQ_SE_GS_PHONE0
	WaitFanfare SEQ_SE_GS_PHONE0
	PlayFanfare SEQ_SE_GS_PHONE0
	WaitFanfare SEQ_SE_GS_PHONE0
	FadeScreen 6 1 0 0
	WaitFadeScreen
	StartPokeGearCall
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
Return

Function 31:
	LocalScript
End

Function 32:
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	LocalScript
End

Function 33:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 321 255 0
	CreateMultiTouchBox 322 255 1
	CreateMultiTouchBox 323 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#75
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#76
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#77
End

Function 34:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 6
	FreezeMessage
Jump Function#33

Function 35:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 321 255 0
	CreateMultiTouchBox 322 255 1
	CreateMultiTouchBox 323 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#78
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#79
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#80
End

Function 36:
	CheckFlag 367
	JumpIf EQUAL Function#81
	CheckFlag 368
	JumpIf EQUAL Function#82
	CheckFlag 369
	JumpIf EQUAL Function#83
	CheckFlag 394
	JumpIf EQUAL Function#84
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 6
	FreezeMessage
Jump Function#35

Function 37:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 2
Jump Function#85

Function 38:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 3
Jump Function#85

Function 39:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 4
Jump Function#85

Function 40:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 5
Jump Function#85

Function 41:
	UseScript_#58

Function 42:
	UseScript_#59

Function 43:
	UseScript_#60

Function 44:
	UseScript_#62

Function 45:
	UseScript_#63

Function 46:
	UseScript_#64

Function 47:
	CloseMessage
	ReleaseAll
End

Function 48:
	PlaySound SEQ_ME_KEYITEM
Return

Function 49:
	PlaySound SEQ_ME_ITEM
Return

Function 50:
	PlaySound SEQ_ME_HYOUKA2
Return

Function 51:
	PlaySound SEQ_ME_WAZA
Return

Function 52:
	TextPlayerName 0
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#53
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 53:
	SetVar 0x8004 1
Jump Function#6

Function 54:
	SetPlayerForm 256
	UpdatePlayerForm
	Movement Player Action#3
	WaitMovement
	FollowingPokePCAnimation
	CheckTrainerCardLevel 0x800C
	CompareVarValue 0x800C 4
	CallIf GREATER/EQUAL Function#86
	CompareVarValue 0x800C 4
	CallIf LESS Function#87
	Call Function#71
	CheckFlag 101
	JumpIf LESS Function#88
Jump Function#89

Function 55:
	UpdatePlayerForm
	Movement Player Action#3
	WaitMovement
	FollowingPokePCAnimation
	CheckTrainerCardLevel 0x800C
	CompareVarValue 0x800C 4
	CallIf GREATER/EQUAL Function#86
	CompareVarValue 0x800C 4
	CallIf LESS Function#87
	Call Function#71
	CheckFlag 101
	JumpIf LESS Function#88
Jump Function#89

Function 56:
	HideSaveBox
	CloseTouchScreen
	SetVar 0x800C 0
Return

Function 57:
	HideSaveBox
	CloseTouchScreen
	Message 20
	WaitButton
	SetVar 0x800C 0
Return

Function 58:
	Message 21
Jump Function#90

Function 59:
	Message 14
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#56
	Message 21
Jump Function#90

Function 60:
	Message 14
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#56
	CheckFlag 32
	JumpIf LESS Function#91
	CheckFlag 32
	JumpIf EQUAL Function#92
End

Function 61:
	TextPlayerName 0
	TextItemLowercase 1 0x8004
	Message 28
Jump Function#93

Function 62:
	CompareVarValue 0x8005 1
	JumpIf GREATER Function#94
	TextItemLowercase 0 0x8004
Jump Function#95

Function 63:
	Message 31
	WaitButton
Return

Function 64:
	WaitButton
Return

Function 65:
Return

Function 66:
	CreateMultiTouchBox 61 255 0
Return

Function 67:
	CreateMultiTouchBox 62 255 0
Return

Function 68:
	CreateMultiTouchBox 64 255 2
	CreateMultiTouchBox 66 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x8006
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#96
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#97
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#98
Jump Function#99

Function 69:
	CreateMultiTouchBox 66 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x8006
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#96
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#97
Jump Function#99

Function 70:
	GetCurrentHeaderID 0x8004
	CompareVarValue 0x8004 69
	JumpIf EQUAL Function#100
	CompareVarValue 0x8004 158
	JumpIf EQUAL Function#101
	CompareVarValue 0x8004 166
	JumpIf EQUAL Function#102
	CompareVarValue 0x8004 236
	JumpIf EQUAL Function#103
	CompareVarValue 0x8004 185
	JumpIf EQUAL Function#104
	CompareVarValue 0x8004 81
	JumpIf EQUAL Function#105
	CompareVarValue 0x8004 246
	JumpIf EQUAL Function#106
	CompareVarValue 0x8004 293
	JumpIf EQUAL Function#107
	CompareVarValue 0x8004 169
	JumpIf EQUAL Function#108
	SetVar 0x8007 0
Return

Function 71:
	Movement 0x8007 Action#5
	WaitMovement
	CountPartyBornPokemon 0x8006
	PCHealAnimation 0x8006
	Movement 0x8007 Action#6
	WaitMovement
	GetFirstAlivePokemonSlot 0x8008
	HealPokemon
Return

Function 72:
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#109
	SetPlayerForm 1024
Jump Function#110

Function 73:
	SetPlayerForm 1
	UpdatePlayerForm
	Movement 0x8007 Action#7
	WaitMovement
	Message 46
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 74:
	UpdatePlayerForm
	Movement 0x8007 Action#7
	WaitMovement
	Message 46
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 75:
	UseScript_#50

Function 76:
	UseScript_#51

Function 77:
	UseScript_#52

Function 78:
	UseScript_#54

Function 79:
	UseScript_#55

Function 80:
	UseScript_#56

Function 81:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 7
Jump Function#111

Function 82:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 8
Jump Function#111

Function 83:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 9
Jump Function#111

Function 84:
	GetCommonMessageArchive 3 0x800C
	MessageFromArchive 0x800C 10
Jump Function#111

Function 85:
	WaitButton
	CloseMessage
	LocalScript
End

Function 86:
	Message 7
Return

Function 87:
	Message 1
Return

Function 88:
	CheckPokerus 0x8006
	CompareVarValue 0x8006 1
	JumpIf EQUAL Function#112
Jump Function#89

Function 89:
	CompareVarValue 0x8004 1
	JumpIf EQUAL Function#113
	Message 2
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#114
	SetPlayerForm 1024
Jump Function#115

Function 90:
	PlayerMovementSavingSet
	WaitTime 2 0x800C
	Call Function#116
	PlayerMovementSavingClear
Jump Function#117

Function 91:
	Message 15
Jump Function#90

Function 92:
	CMD_642 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#118
Jump Function#91

Function 93:
	WaitSound
	TextPlayerName 0
	CompareVarValue 0x8005 1
	JumpIf GREATER Function#119
	TextItem 1 0x8004
Jump Function#120

Function 94:
	TextItemPlural 0 0x8004
	Message 25
Jump Function#93

Function 95:
	Message 25
Jump Function#93

Function 96:
	PlayFanfare SEQ_SE_DP_PC_LOGIN
	TextPlayerName 0
	Message 35
	Call Function#121
Jump Function#122

Function 97:
	PlayFanfare SEQ_SE_DP_PC_LOGIN
	TextPlayerName 0
	Message 36
Jump Function#123

Function 98:
	PlayFanfare SEQ_SE_DP_PC_LOGIN
	CloseMessage
	CMD_706 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#124
	Call Function#125
	HallOfFameData
	ReturnScreen
	Call Function#126
Jump Function#16

Function 99:
	CloseMessage
	PlayFanfare SEQ_SE_DP_PC_LOGOFF
	CheckFlag 399
	JumpIf EQUAL Function#127
	Call Function#128
	ClearFlag 399
	CloseTouchScreen
	ReleaseAll
End

Function 100:
	SetVar 0x8007 0
Return

Function 101:
	SetVar 0x8007 3
Return

Function 102:
	SetVar 0x8007 6
Return

Function 103:
	SetVar 0x8007 3
Return

Function 104:
	SetVar 0x8007 0
Return

Function 105:
	SetVar 0x8007 0
Return

Function 106:
	SetVar 0x8007 2
Return

Function 107:
	SetVar 0x8007 3
Return

Function 108:
	SetVar 0x8007 3
Return

Function 109:
	SetPlayerForm 1
	UpdatePlayerForm
	Movement 0x8007 Action#7
	WaitMovement
	Message 40
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 110:
	UpdatePlayerForm
	Movement 0x8007 Action#7
	WaitMovement
	Message 40
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 111:
	FreezeMessage
Jump Function#35

Function 112:
	SetFlag 101
	CMD_148 1 0
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#129
	SetPlayerForm 1024
Jump Function#130

Function 113:
	Message 8
	Movement Player Action#4
	WaitMovement
	CheckPlayerForm 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#131
	SetPlayerForm 1024
Jump Function#132

Function 114:
	SetPlayerForm 1
	UpdatePlayerForm
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#133
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Movement 0x8007 Action#7
	WaitMovement
	Message 3
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 115:
	UpdatePlayerForm
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#133
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Movement 0x8007 Action#7
	WaitMovement
	Message 3
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 116:
	AddWaitingIcon
	CheckFlag 32
	CallIf EQUAL Function#134
	SaveGame 0x800C
	RemoveWaitingIcon
Return

Function 117:
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#135
	TextPlayerName 0
	Message 16
	PlayFanfare SEQ_SE_DP_SAVE
	WaitFanfare SEQ_SE_DP_SAVE
	WaitTimeOrAB 30
	HideSaveBox
Return

Function 118:
	Message 21
Jump Function#90

Function 119:
	TextItemPlural 1 0x8004
	GetItemPocket 0x8004 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 7
	JumpIf EQUAL Function#136
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#137
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#138
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#139
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#140
	CompareVarValue 0x8008 6
	JumpIf EQUAL Function#141
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#142
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#143
End

Function 120:
	GetItemPocket 0x8004 0x800C
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 7
	JumpIf EQUAL Function#136
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#137
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#138
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#139
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#140
	CompareVarValue 0x8008 6
	JumpIf EQUAL Function#141
	CompareVarValue 0x8008 5
	JumpIf EQUAL Function#142
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#143
End

Function 121:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 67 76 0
	CreateMultiTouchBox 68 77 1
	CreateMultiTouchBox 69 78 2
	CreateMultiTouchBox 70 79 3
	CreateMultiTouchBox 72 81 5
Return

Function 122:
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#144
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#145
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#146
	CompareVarValue 0x8008 3
	JumpIf EQUAL Function#147
	CompareVarValue 0x8008 4
	JumpIf EQUAL Function#148
Jump Function#16

Function 123:
	Call Function#149
	CMD_616 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#150
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#151
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#152
Jump Function#16

Function 124:
	Message 94
Jump Function#16

Function 125:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CheckFlag 399
	JumpIf EQUAL Function#153
	FreeDoor 90
Return

Function 126:
	Call Function#15
	FadeScreen 6 1 1 0
	WaitFadeScreen
Return

Function 127:
	ClearFlag 399
	CloseTouchScreen
	ReleaseAll
End

Function 128:
	ClosePCAnimation 90
	WaitDoor 90
	FreeDoor 90
Return

Function 129:
	SetPlayerForm 1
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#154
	UpdatePlayerForm
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Message 10
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 130:
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#154
	UpdatePlayerForm
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Message 10
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 131:
	SetPlayerForm 1
	UpdatePlayerForm
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#155
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Movement 0x8007 Action#7
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 132:
	UpdatePlayerForm
	GetFirstAlivePokemonSlot 0x8009
	CompareVars 0x8008 0x8009
	JumpIf EQUAL Function#155
	WaitTime 15 0x800A
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	FinishOverworldScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	TextPokeNickname 0 0x8009
	Message 102
	Movement 0x8007 Action#7
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 133:
	Movement 0x8007 Action#7
	WaitMovement
	Message 3
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 134:
	SaveWipeExtraChunks
	ClearFlag 32
Return

Function 135:
	Message 18
	WaitButton
	HideSaveBox
	CloseTouchScreen
Return

Function 136:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 137:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 138:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 139:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 140:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 141:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 142:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 143:
	GetItemPocket 0x8004 0x800C
	TextPocket 2 0x800C
Jump Function#156

Function 144:
	CloseMessage
	Call Function#125
	PCBoxScreen 0
	ReturnScreen
Jump Function#157

Function 145:
	CloseMessage
	Call Function#125
	PCBoxScreen 1
	ReturnScreen
Jump Function#157

Function 146:
	CloseMessage
	Call Function#125
	PCBoxScreen 2
	ReturnScreen
Jump Function#157

Function 147:
	CloseMessage
	Call Function#125
	PCBoxScreen 3
	ReturnScreen
Jump Function#157

Function 148:
	CloseMessage
	Call Function#125
	PCBoxScreen 4
	ReturnScreen
Jump Function#157

Function 149:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 73 82 0
	CreateMultiTouchBox 74 83 1
	CMD_616 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#158
	CreateMultiTouchBox 75 84 2
Return

Function 150:
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#151
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#152
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#159
Jump Function#16

Function 151:
	CloseMessage
	CountMail 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#160
	Call Function#125
	MailScreen
	ReturnScreen
Jump Function#161

Function 152:
	GetUniqueSealsQuantity 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#162
	CloseMessage
	Call Function#125
	SealCapsuleScreen
Jump Function#163

Function 153:
Return

Function 154:
	Message 10
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
	LocalScript
End

Function 155:
	Movement 0x8007 Action#7
	WaitMovement
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	LocalScript
End

Function 156:
Return

Function 157:
	TextPlayerName 0
	MessageAll 34
	Call Function#121
	Call Function#15
	FadeScreen 6 1 1 0
Jump Function#122

Function 158:
	CreateMultiTouchBox 65 85 2
	CreateMultiTouchBox 75 84 3
Return

Function 159:
	CloseMessage
	Call Function#125
	CMD_617
	ReturnScreen
Jump Function#164

Function 160:
	Message 47
Jump Function#123

Function 161:
	TextPlayerName 0
	MessageAll 34
	Call Function#149
	Call Function#15
	FadeScreen 6 1 1 0
Jump Function#165

Function 162:
	Message 79
Jump Function#123

Function 163:
	TextPlayerName 0
	MessageAll 34
	Call Function#149
	Call Function#15
	FadeScreen 6 1 1 0
Jump Function#165

Function 164:
	TextPlayerName 0
	MessageAll 34
	Call Function#149
	Call Function#15
	FadeScreen 6 1 1 0
Jump Function#165

Function 165:
	CMD_616 0x4000
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#150
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#151
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#152
Jump Function#16

//===== ACTIONS =====//
Action 1:
	FaceNorth 0x1
End

Action 2:
	FaceSouth 0x1
End

Action 3:
	PlayerGive 0x1
End

Action 4:
	PlayerReceive 0x1
End

Action 5:
	FaceWest 0x1
End

Action 6:
	FaceSouth 0x1
End

Action 7:
	NurseJoyBow 0x1
	Delay4 0x1
End

