/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0061
 * Generated: 9/2/2026 12:10:04 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 122
	JumpIf EQUAL Function#1
	Message 0
	WaitAB
	CloseMessage
	SetVar 0x8004 221
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#2
	CommonScript 2033
	SetFlag 122
Jump Function#1

Script 2:
	LockAll
	FacePlayer
	PlayCry SPECIES_UXIE 0
	Message 3
	WaitCry
	CloseMessage
	PlayFanfare SEQ_GS_D_CHIKATSUURO_PHC
	WildBattleSp SPECIES_UXIE 75 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GetBattleOutcome 0x401A
	CompareVarValue 0x401A 3
	JumpIf EQUAL Function#4
	CompareVarValue 0x401A 4
	JumpIf EQUAL Function#5
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	ReleaseAll
End

Function 5:
	SetFlag 2553
	RemoveOW Overworld.2
	ReleaseAll
End

//===== ACTIONS =====//
