/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0092
 * Generated: 9/2/2026 12:10:04 PM
 */

//===== SCRIPTS =====//
Script 1:
	GetCounterpartSprite 0x4020
	CheckFlag 393
	JumpIf LESS Function#1
	ClearFlag 393
Jump Function#2

Script 2:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4000 25
	JumpIf DIFFERENT Function#3
Jump Function#4

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 11
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	Message 14
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#6
	GetPartyPokemonID 0x800C 0x8005
	SetVarFromFlexible 0x8006 0x800C
	CompareVarValue 0x8005 0
	JumpIf EQUAL Function#7
	CheckPokemonHasMove 0x800C MOVE_HEADBUTT 0x8006
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	CheckHeadbuttCompatibility 0x8006 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	Message 16
	CloseMessage
Jump Function#10

Script 4:
	MecScript
	LockAll
	CompareVarValue 0x4004 1
	JumpIf EQUAL Function#11
	SetVar 0x4002 1
	SetVar 0x4099 2
	SetVar 0x409B 1
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4000 25
	JumpIf DIFFERENT Function#12
Jump Function#13

Script 5:
	MecScript
	LockAll
	CompareVarValue 0x4004 1
	JumpIf EQUAL Function#11
	SetVar 0x4099 1
	SetVar 0x409B 2
	SetVar 0x4002 0
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4000 25
	JumpIf DIFFERENT Function#14
Jump Function#15

Script 6:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4000 41
	JumpIf DIFFERENT Function#16
Jump Function#17

Script 7:
	MecScript
	LockAll
	SetVar 0x4003 0
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4000 41
	JumpIf DIFFERENT Function#18
Jump Function#19

Script 8:
	MecScript
	LockAll
	SetVar 0x4003 1
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4000 41
	JumpIf DIFFERENT Function#20
Jump Function#21

Script 9:
	MecScript
	LockAll
	SetVar 0x4003 0
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4000 41
	JumpIf DIFFERENT Function#22
Jump Function#23

Script 10:
	MecScript
	LockAll
	SetVar 0x4003 0
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4000 41
	JumpIf DIFFERENT Function#24
Jump Function#25

Script 11:
	CheckFlag 125
	JumpIf EQUAL Function#26
Jump Function#27

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 128
	JumpIf EQUAL Function#28
	Message 6
	SetVar 0x8004 420
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#29
	CommonScript 2033
	SetFlag 128
	ClearFlag 430
	ClearFlag 428
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 13:
	CheckBike 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#30
	CompareVarValue 0x412B 2
	JumpIf GREATER/EQUAL Function#31
	CompareVarValue 0x412B 1
	JumpIf EQUAL Function#30
	GetFirstAlivePokemonSlot 0x4000
	FollowingPokemonIsEventTrigger 0 0x4000 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#32
Jump Function#31

Script 14:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 27 0x800C
	CommonScript 2000
End

Script 15:
	PlayCry SPECIES_FARFETCHD 0
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	MecScript
	LockAll
	CommonScript 2067
	Movement Overworld.12 Action#1
	WaitMovement
	GetPlayerPosition 0x8004 0x8005
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#33
	Movement Overworld.12 Action#2
Jump Function#34

Script 17:
	MecScript
	LockAll
	Movement Player Action#3
	WaitMovement
	Movement Overworld.1 Action#4
	WaitMovement
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ShakeCamera 0 2 10 5
	Movement Overworld.1 Action#5
	WaitMovement
	Movement Overworld.1 Action#4
	WaitMovement
	PlayFanfare SEQ_SE_DP_KI_GASYAN
	ShakeCamera 0 2 10 5
	Movement Overworld.1 Action#5
	WaitMovement
	SetVar 0x40EA 1
	ReleaseAll
End

Script 18:
	MecScript
	LockAll
	Movement Overworld.3 Action#6
	Movement Player Action#7
	WaitMovement
	Message 0
	WaitButton
	CloseMessage
	SetVar 0x40F4 0
	ReleaseAll
End

Script 19:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#35
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#36
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 1
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#37
	Movement Player Action#8
	Movement Overworld.13 Action#9
Jump Function#38

Script 20:
	MecScript
	LockAll
	SetVar 0x4008 1
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#39
	Movement Overworld.14 Action#10
Jump Function#40

Script 21:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4008 1
	Call Function#41
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#42
	Call Function#43
Jump Function#44

Script 22:
	CompareVarValue 0x412B 1
	CallIf EQUAL Function#45
	CompareVarValue 0x40FE 4
	CallIf EQUAL Function#46
End

Script 23:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.16 Action#11
	Movement Player Action#12
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	GenderMessage 61 60
	CloseMessage
	Movement Overworld.17 Action#13
	WaitMovement
	CommonScript 2029
	Movement Overworld.16 Action#14
	WaitMovement
	GenderMessage 63 62
	CloseMessage
	Movement Overworld.16 Action#15
	WaitMovement
	GenderMessage 65 64
	CloseMessage
	Movement Overworld.16 Action#16
	Movement Overworld.17 Action#17
	WaitMovement
	GenderMessage 67 66
	CloseMessage
	Movement Overworld.16 Action#18
	Movement Overworld.17 Action#19
	WaitMovement
	CommonScript 2030
	CloseTouchScreen
	SetVar 0x40FE 5
	RemoveOW Overworld.16
	RemoveOW Overworld.17
	SetFlag 784
	ReleaseAll
End

Script 24:
	LockAll
	FacePlayer
	PlayCry SPECIES_CELEBI 0
	Message 70
	WaitCry
	CloseMessage
	PlayFanfare SEQ_GS_D_CHIKATSUURO_PHC
	WildBattleSp SPECIES_CELEBI 75 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#47
	GetBattleOutcome 0x401A
	CompareVarValue 0x401A 3
	JumpIf EQUAL Function#48
	CompareVarValue 0x401A 4
	JumpIf EQUAL Function#49
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 2 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#50
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 2
	JumpIf EQUAL Function#51
	CompareVarValue 0x4000 6
	JumpIf EQUAL Function#51
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#51
	SetFlag 638
Jump Function#2

Function 2:
	CheckFlag 123
	JumpIf EQUAL Function#52
End

Function 3:
	CompareVarValue 0x4000 32
	JumpIf DIFFERENT Function#4
Jump Function#53

Function 4:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#54
Jump Function#55

Function 5:
	Message 13
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 6:
	Message 13
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 7:
	Message 15
	CloseMessage
Jump Function#10

Function 8:
	TextPartyPokemon 0 0x8006
	Message 23
	CloseMessage
Jump Function#10

Function 9:
	GetMoveCount 0x8002 0x8006
	CompareVarValue 0x8002 3
	JumpIf LESS/EQUAL Function#56
	OpenTouchScreen
	TextPokeNickname 0 0x8006
	Message 17
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#57
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PokemonSummaryScreen 1 0x8006 MOVE_HEADBUTT
	GetMoveSelection 1 0x8001
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8001 4
	JumpIf EQUAL Function#58
	TextPartyPokemonMove 1 0x8006 0x8001
	Message 18
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#57
	ReplaceMove 0x8006 0x8001 MOVE_HEADBUTT
	Message 20
	PlayFanfare SEQ_SE_DP_KON
	WaitFanfare SEQ_SE_DP_KON
	WaitTime 30 0x800C
	Message 24
	WaitTime 32 0x800C
	Message 25
	PlaySound SEQ_ME_LVUP
	WaitSound
	WaitTime 16 0x800C
	PlayCry 0x8005 0
Jump Function#59

Function 10:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#6
	GetPartyPokemonID 0x800C 0x8005
	SetVarFromFlexible 0x8006 0x800C
	CompareVarValue 0x8005 0
	JumpIf EQUAL Function#7
	CheckPokemonHasMove 0x800C MOVE_HEADBUTT 0x8006
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	CheckHeadbuttCompatibility 0x8006 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	Message 16
	CloseMessage
Jump Function#10

Function 11:
	SetVar 0x4099 2
	SetVar 0x409B 2
	Movement Overworld.0 Action#20
	WaitMovement
	ReleaseAll
End

Function 12:
	CompareVarValue 0x4000 32
	JumpIf DIFFERENT Function#13
Jump Function#60

Function 13:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#61
Jump Function#62

Function 14:
	CompareVarValue 0x4000 32
	JumpIf DIFFERENT Function#15
Jump Function#63

Function 15:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#64
Jump Function#65

Function 16:
	CompareVarValue 0x4000 49
	JumpIf DIFFERENT Function#17
Jump Function#66

Function 17:
	SetVar 0x4003 0
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#67
Jump Function#68

Function 18:
	CompareVarValue 0x4000 49
	JumpIf DIFFERENT Function#19
Jump Function#69

Function 19:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#70
Jump Function#71

Function 20:
	CompareVarValue 0x4000 49
	JumpIf DIFFERENT Function#21
Jump Function#72

Function 21:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#73
Jump Function#74

Function 22:
	CompareVarValue 0x4000 49
	JumpIf DIFFERENT Function#23
Jump Function#75

Function 23:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#76
Jump Function#77

Function 24:
	CompareVarValue 0x4000 49
	JumpIf DIFFERENT Function#25
Jump Function#78

Function 25:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#79
Jump Function#80

Function 26:
	CheckFlag 126
	JumpIf EQUAL Function#81
Jump Function#82

Function 27:
	CheckFlag 126
	JumpIf EQUAL Function#82
Jump Function#83

Function 28:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 29:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 30:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 28
	CompareVarValue 0x416E 1
	JumpIf EQUAL Function#84
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 31:
	CompareVarValue 0x40FE 4
	JumpIf GREATER/EQUAL Function#30
	CheckFlag 198
	JumpIf LESS Function#30
	GetFirstAlivePokemonSlot 0x4006
	GetPartyPokemonID 0x4006 0x4007
	CompareVarValue 0x4007 251
	JumpIf EQUAL Function#85
Jump Function#30

Function 32:
	ClearFlag 667
Jump Function#86

Function 33:
	Movement Overworld.12 Action#21
	WaitMovement
	Message 29
	CloseMessage
	Movement Overworld.12 Action#22
	WaitMovement
	Message 30
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#87
	Message 31
Jump Function#88

Function 34:
	WaitMovement
	Message 29
	CloseMessage
	Movement Overworld.12 Action#22
	WaitMovement
	Message 30
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#87
	Message 31
Jump Function#88

Function 35:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 36:
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 37:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#89
	Movement Player Action#23
Jump Function#38

Function 38:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#90
	Movement Following Action#24
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 8
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 39:
	CompareVarValue 0x4005 2
	JumpIf DIFFERENT Function#91
	Movement Overworld.14 Action#25
Jump Function#40

Function 40:
	WaitMovement
	PlayCry SPECIES_PICHU 0
	Message 43
	WaitCry
	CloseMessage
	Call Function#41
	CompareVarValue 0x8004 1
	JumpIf GREATER/EQUAL Function#92
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#93
	Movement Overworld.15 Action#26
Jump Function#94

Function 41:
	GetPartyCount 0x800C
	CompareVarValue 0x800C 6
	JumpIf LESS Function#95
	SetVar 0x8004 1
Jump Function#96

Function 42:
	Call Function#97
	ReleaseAll
End

Function 43:
	Message 55
	WaitButton
	CloseMessage
Return

Function 44:
	ReleaseAll
End

Function 45:
	SetOWPosition Overworld.15 15 0 58 Down
	SetOWPosition Overworld.14 15 0 59 Right
Return

Function 46:
	SetOWPosition Overworld.16 15 0 58 Down
	SetOWPosition Overworld.17 11 0 58 Right
Return

Function 47:
	LostBattle
	ReleaseAll
End

Function 48:
	ReleaseAll
End

Function 49:
	IncrementVar 0x416E 1
	RemoveOW Overworld.18
	ReleaseAll
End

Function 50:
	SetFlag 638
Jump Function#2

Function 51:
	ClearFlag 638
	CheckFlag 123
	JumpIf EQUAL Function#52
End

Function 52:
	SetVar 0x4099 1
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 1
	SetVar 0x4000 0
	SetVar 0x4001 0
	SetVar 0x4002 0
	SetVar 0x4003 0
	SetVar 0x4004 0
	CheckFlag 125
	JumpIf EQUAL Function#98
	CheckFlag 126
	JumpIf EQUAL Function#99
End

Function 53:
	SetVar 0x4002 0
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#100
Jump Function#101

Function 54:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#53
Jump Function#102

Function 55:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4002 0
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#103
	Movement Overworld.0 Action#27
Jump Function#104

Function 56:
	TextPokeNickname 0 0x8006
	ReplaceMove 0x8006 0x8002 MOVE_HEADBUTT
	Message 21
	WaitTime 30 0x800C
	Message 26
	PlaySound SEQ_ME_LVUP
	WaitSound
	WaitTime 32 0x800C
	PlayCry 0x8005 0
	Message 22
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 57:
	Message 19
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#105
Jump Function#5

Function 58:
	Message 19
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#105
Jump Function#5

Function 59:
	Message 22
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 60:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#106
Jump Function#107

Function 61:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#60
Jump Function#108

Function 62:
	Movement Overworld.0 Action#28
	WaitMovement
	ReleaseAll
End

Function 63:
	GetOWPosition Overworld.0 0x4000 0x4001
	CompareVarValue 0x4001 52
	JumpIf DIFFERENT Function#109
Jump Function#110

Function 64:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#63
Jump Function#111

Function 65:
	Movement Overworld.0 Action#28
	WaitMovement
	ReleaseAll
End

Function 66:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#112
Jump Function#113

Function 67:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#66
Jump Function#114

Function 68:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#115
	Movement Overworld.2 Action#29
	WaitMovement
	SetVar 0x409A 1
	SetVar 0x409C 1
	SetVar 0x409D 2
	SetVar 0x409E 2
Jump Function#116

Function 69:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#117
Jump Function#118

Function 70:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#69
Jump Function#119

Function 71:
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 72:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#120
Jump Function#121

Function 73:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#72
Jump Function#122

Function 74:
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 75:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#123
Jump Function#124

Function 76:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#75
Jump Function#125

Function 77:
	Movement Overworld.2 Action#28
	WaitMovement
	ReleaseAll
End

Function 78:
	GetOWPosition Overworld.2 0x4000 0x4001
	CompareVarValue 0x4001 54
	JumpIf DIFFERENT Function#126
Jump Function#127

Function 79:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#78
Jump Function#128

Function 80:
	SetVar 0x409E 2
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 81:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 82:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 83:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	SetVar 0x40F4 0
	ReleaseAll
End

Function 84:
	Message 69
	WaitButton
	CloseMessage
	Movement Player Action#31
	Movement Following Action#32
	WaitMovement
	SetOWPosition Overworld.18 16 0 52 Down
	Movement Overworld.18 Action#33
	WaitMovement
	ReleaseAll
End

Function 85:
Jump Function#129

Function 86:
	MecScript
	LockAll
	StopMusic 0
	ClearFlag 667
	AddOW Overworld.14
	Movement Overworld.14 Action#31
	WaitMovement
	PlayCry SPECIES_PICHU 0
	WaitCry
	Movement Player Action#32
	WaitMovement
	CommonScript 2065
	Movement Overworld.14 Action#34
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#35
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 38
	CloseMessage
	Movement Following Action#36
	WaitMovement
	Movement Overworld.14 Action#37
	WaitMovement
	Movement Following Action#38
	WaitMovement
	Movement Overworld.14 Action#39
	Movement Following Action#40
	WaitMovement
	ClearFlag 668
	AddOW Overworld.15
	Movement Overworld.15 Action#41
	Movement Overworld.14 Action#42
	Movement Following Action#43
	WaitMovement
	Movement Player Action#44
	WaitMovement
	Message 46
	CloseMessage
	Movement Overworld.15 Action#45
	WaitMovement
	Message 47
	CloseMessage
	Movement Overworld.15 Action#46
	Movement Overworld.14 Action#47
	Movement Player Action#48
	WaitMovement
	Message 48
	CloseMessage
	Movement Overworld.14 Action#49
	Movement Following Action#50
	WaitMovement
	Message 49
	CloseMessage
	Movement Following Action#51
	WaitMovement
	Movement Overworld.14 Action#52
	WaitMovement
	Movement Following Action#53
	WaitMovement
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#54
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Message 39
	PlayCry SPECIES_PICHU 0
	Message 43
	WaitCry
	CloseMessage
	Call Function#41
	CompareVarValue 0x8004 1
	CallIf GREATER/EQUAL Function#97
	CompareVarValue 0x8004 0
	CallIf EQUAL Function#130
	ReleaseAll
End

Function 87:
	Message 32
	CloseMessage
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 50
	JumpIf EQUAL Function#131
	CompareVarValue 0x4001 51
	JumpIf EQUAL Function#131
	Release Following
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#132
	Movement Player Action#55
	Movement Following Action#56
Jump Function#133

Function 88:
	CloseMessage
	GetFirstAlivePokemonSlot 0x4000
	GetPartyPokemonID 0x4000 0x4001
	CompareVarValue 0x4001 50
	JumpIf EQUAL Function#131
	CompareVarValue 0x4001 51
	JumpIf EQUAL Function#131
	Release Following
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#132
	Movement Player Action#55
	Movement Following Action#56
Jump Function#133

Function 89:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#134
	Movement Player Action#57
	Movement Overworld.13 Action#9
Jump Function#38

Function 90:
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 8
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 91:
	Movement Overworld.14 Action#58
	WaitMovement
	PlayCry SPECIES_PICHU 0
	Message 43
	WaitCry
	CloseMessage
	Call Function#41
	CompareVarValue 0x8004 1
	JumpIf GREATER/EQUAL Function#92
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#93
	Movement Overworld.15 Action#26
Jump Function#94

Function 92:
	Message 42
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 93:
	CompareVarValue 0x4005 2
	JumpIf DIFFERENT Function#135
	Movement Overworld.15 Action#59
Jump Function#94

Function 94:
	WaitMovement
	Message 52
	CloseMessage
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#136
	Movement Player Action#60
Jump Function#137

Function 95:
	SetVar 0x8004 0
Return

Function 96:
Return

Function 97:
	Message 50
	WaitButton
	CloseMessage
	CompareVarValue 0x4008 0
	JumpIf DIFFERENT Function#138
	CommonScript 2066
	SetVar 0x412B 1
Return

Function 98:
	CheckFlag 126
	JumpIf EQUAL Function#139
	SetVar 0x4099 2
End

Function 99:
	SetVar 0x4099 1
	SetVar 0x409E 2
End

Function 100:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#55
Jump Function#140

Function 101:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#141
	Movement Overworld.0 Action#61
	SetVar 0x409B 1
	SetVar 0x4099 1
	SetVar 0x4004 1
Jump Function#142

Function 102:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#143
Jump Function#144

Function 103:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#104
	Movement Overworld.0 Action#61
	SetVar 0x409B 1
	SetVar 0x4099 1
	WaitMovement
	ReleaseAll
End

Function 104:
	WaitMovement
	ReleaseAll
End

Function 105:
	TextPokeNickname 0 0x8006
	Message 17
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#57
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PokemonSummaryScreen 1 0x8006 MOVE_HEADBUTT
	GetMoveSelection 1 0x8001
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8001 4
	JumpIf EQUAL Function#58
	TextPartyPokemonMove 1 0x8006 0x8001
	Message 18
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#57
	ReplaceMove 0x8006 0x8001 MOVE_HEADBUTT
	Message 20
	PlayFanfare SEQ_SE_DP_KON
	WaitFanfare SEQ_SE_DP_KON
	WaitTime 30 0x800C
	Message 24
	WaitTime 32 0x800C
	Message 25
	PlaySound SEQ_ME_LVUP
	WaitSound
	WaitTime 16 0x800C
	PlayCry 0x8005 0
Jump Function#59

Function 106:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#62
Jump Function#145

Function 107:
	Movement Overworld.0 Action#28
	WaitMovement
	ReleaseAll
End

Function 108:
	Movement Overworld.0 Action#28
	WaitMovement
	CheckFlag 293
	JumpIf EQUAL Function#146
	Message 35
	WaitButton
	CloseMessage
	SetFlag 293
	ReleaseAll
End

Function 109:
	CompareVarValue 0x4001 62
	JumpIf DIFFERENT Function#65
Jump Function#147

Function 110:
	Movement Overworld.0 Action#28
	WaitMovement
	ReleaseAll
End

Function 111:
	Movement Overworld.0 Action#30
	WaitMovement
	ReleaseAll
End

Function 112:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#68
Jump Function#148

Function 113:
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#149
Jump Function#150

Function 114:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#151
	Movement Overworld.2 Action#29
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 2
Jump Function#152

Function 115:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#116
	Movement Overworld.2 Action#61
	WaitMovement
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 1
	SetVar 0x409E 2
	CheckFlag 294
	JumpIf EQUAL Function#153
	Message 36
	WaitButton
	CloseMessage
	SetFlag 294
	ReleaseAll
End

Function 116:
	CheckFlag 294
	JumpIf EQUAL Function#153
	Message 36
	WaitButton
	CloseMessage
	SetFlag 294
	ReleaseAll
End

Function 117:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#71
Jump Function#154

Function 118:
	SetVar 0x409A 2
	SetVar 0x409C 1
	SetVar 0x409D 2
	SetVar 0x409E 1
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 119:
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 120:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#74
Jump Function#155

Function 121:
	SetVar 0x409A 1
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 1
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 122:
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 123:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#77
Jump Function#156

Function 124:
	Movement Overworld.2 Action#28
	WaitMovement
	ReleaseAll
End

Function 125:
	SetVar 0x409D 2
	Movement Overworld.2 Action#30
	WaitMovement
	ReleaseAll
End

Function 126:
	CompareVarValue 0x4001 64
	JumpIf DIFFERENT Function#80
Jump Function#157

Function 127:
	SetVar 0x409A 1
	SetVar 0x409C 1
	SetVar 0x409E 2
	Movement Overworld.2 Action#20
	WaitMovement
	ReleaseAll
End

Function 128:
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 129:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Movement Following Action#63
	WaitMovement
	FadeOutMusic 0 30
	CommonScript 2029
	OpenTouchScreen
	ClearFlag 784
	AddOW Overworld.16
	AddOW Overworld.17
	Movement Overworld.16 Action#64
	Movement Overworld.17 Action#65
	WaitMovement
	Movement Player Action#66
	WaitMovement
	GenderMessage 57 56
	CloseMessage
	CommonScript 2030
	PlayFanfare SEQ_SE_GS_SUZUSYUTUGEN_HO
	FadeScreen 6 6 0 0x7FFF
	WaitFadeScreen
	WaitTime 15 0x800C
	FadeScreen 6 6 1 0x7FFF
	WaitFadeScreen
	Movement Player Action#67
	Movement Overworld.16 Action#68
	WaitMovement
	GenderMessage 59 58
	CloseMessage
	PlayFanfare SEQ_SE_GS_TIMESLIP
	CelebiTimeTravelAnimation
	SetVar 0x40FE 1
	ClearFlag 769
	ClearFlag 770
	SetFlag 784
	Warp 27 0 954 280 Down
	FadeScreen 6 15 1 0x7FFF
	WaitFadeScreen
	ReleaseAll
End

Function 130:
	Message 52
	CloseMessage
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Player Action#69
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#158
	Movement Overworld.15 Action#26
Jump Function#159

Function 131:
	Release Following
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#160
	Movement Player Action#55
	Movement Following Action#70
Jump Function#161

Function 132:
	Movement Following Action#71
	WaitMovement
	Lock Following
Jump Function#162

Function 133:
	WaitMovement
	Lock Following
Jump Function#162

Function 134:
	StopFanfare SEQ_SE_GS_N_SESERAGI
	Movement Player Action#72
	Movement Overworld.13 Action#9
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#90
	Movement Following Action#24
	WaitMovement
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 8
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	GetCommonMessageArchive 2 0x800C
	MessageFromArchive 0x800C 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 135:
	Movement Overworld.15 Action#73
	WaitMovement
	Message 52
	CloseMessage
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#136
	Movement Player Action#60
Jump Function#137

Function 136:
	CompareVarValue 0x4005 2
	JumpIf DIFFERENT Function#163
	Movement Player Action#69
Jump Function#137

Function 137:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Call Function#164
Jump Function#165

Function 138:
	SetVar 0x412B 1
Return

Function 139:
	SetVar 0x4099 2
	SetVar 0x409E 2
End

Function 140:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4004 0
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#166
	Movement Overworld.0 Action#74
	SetVar 0x4099 2
	SetVar 0x409B 2
Jump Function#167

Function 141:
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#142
	Movement Overworld.0 Action#75
	SetVar 0x4099 2
	SetVar 0x409B 2
	WaitMovement
	ReleaseAll
End

Function 142:
	WaitMovement
	ReleaseAll
End

Function 143:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#144
Jump Function#168

Function 144:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4099 2
	SetVar 0x409B 2
	Movement Overworld.0 Action#74
	WaitMovement
	CheckFlag 294
	JumpIf EQUAL Function#169
	Message 36
	WaitButton
	CloseMessage
	SetFlag 294
	ReleaseAll
End

Function 145:
	Movement Overworld.0 Action#20
	WaitMovement
	ReleaseAll
End

Function 146:
	ReleaseAll
End

Function 147:
	Movement Overworld.0 Action#20
	WaitMovement
	ReleaseAll
End

Function 148:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4003 0
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#170
	Movement Overworld.2 Action#74
	SetVar 0x409A 1
	SetVar 0x409C 1
	SetVar 0x409D 2
	SetVar 0x409E 1
Jump Function#171

Function 149:
	CompareVarValue 0x800C 3
	JumpIf DIFFERENT Function#150
Jump Function#172

Function 150:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 2
	Movement Overworld.2 Action#76
	WaitMovement
	ReleaseAll
End

Function 151:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#152
	Movement Overworld.2 Action#74
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 1
	WaitMovement
	ReleaseAll
End

Function 152:
	WaitMovement
	ReleaseAll
End

Function 153:
	ReleaseAll
End

Function 154:
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 155:
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 156:
	SetVar 0x409D 2
	Movement Overworld.2 Action#20
	WaitMovement
	ReleaseAll
End

Function 157:
	Movement Overworld.2 Action#62
	WaitMovement
	ReleaseAll
End

Function 158:
	Movement Overworld.15 Action#59
	WaitMovement
	PlaySound SEQ_ME_ITEM
	TextPlayerName 0
	Message 44
	WaitSound
	Message 53
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#173
	Movement Player Action#77
Jump Function#174

Function 159:
	WaitMovement
	PlaySound SEQ_ME_ITEM
	TextPlayerName 0
	Message 44
	WaitSound
	Message 53
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#173
	Movement Player Action#77
Jump Function#174

Function 160:
	Movement Following Action#78
	WaitMovement
	Lock Following
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#175
	Movement Overworld.12 Action#79
Jump Function#176

Function 161:
	WaitMovement
	Lock Following
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#175
	Movement Overworld.12 Action#79
Jump Function#176

Function 162:
	CompareVarValue 0x8004 40
	JumpIf DIFFERENT Function#175
	Movement Overworld.12 Action#79
Jump Function#176

Function 163:
	Movement Player Action#80
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	Call Function#164
Jump Function#165

Function 164:
	GetPlayerDirection 0x4005
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#158
	Movement Overworld.15 Action#26
Jump Function#159

Function 165:
	ReleaseAll
End

Function 166:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#167
	Movement Overworld.0 Action#75
	SetVar 0x4099 1
	SetVar 0x409B 2
	WaitMovement
	ReleaseAll
End

Function 167:
	WaitMovement
	ReleaseAll
End

Function 168:
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#177
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x4099 2
	SetVar 0x409B 2
	Movement Overworld.0 Action#27
	WaitMovement
	CheckFlag 294
	JumpIf EQUAL Function#178
	Message 36
	WaitButton
	CloseMessage
	SetFlag 294
	ReleaseAll
End

Function 169:
	ReleaseAll
End

Function 170:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#171
	Movement Overworld.2 Action#76
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 2
	WaitMovement
	ReleaseAll
End

Function 171:
	WaitMovement
	ReleaseAll
End

Function 172:
	CompareVarValue 0x4003 1
	JumpIf EQUAL Function#179
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 1
	SetVar 0x409E 2
	Movement Overworld.2 Action#61
	WaitMovement
	ReleaseAll
End

Function 173:
	Movement Player Action#81
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x4008 0
	JumpIf DIFFERENT Function#180
	CommonScript 2066
	GiveSpikyEaredPichu
	RemoveOW Overworld.14
	SetVar 0x412B 2
	PlaySound SEQ_ME_SHINKAOME
	Message 40
	WaitSound
	OpenTouchScreen
	Message 45
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#181
	CloseMessage
	GetPartyCount 0x4009
	DecrementVar 0x4009 1
	SetVar 0x400A 0
	CMD_490 0x4009
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 0x4009 0x400A
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x400A 1
	JumpIf EQUAL Function#181
	TextPokeNickname 0 0x4009
	Message 54
	Message 51
	CloseMessage
	CloseTouchScreen
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#182
	Movement Overworld.15 Action#82
Jump Function#183

Function 174:
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	CompareVarValue 0x4008 0
	JumpIf DIFFERENT Function#180
	CommonScript 2066
	GiveSpikyEaredPichu
	RemoveOW Overworld.14
	SetVar 0x412B 2
	PlaySound SEQ_ME_SHINKAOME
	Message 40
	WaitSound
	OpenTouchScreen
	Message 45
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#181
	CloseMessage
	GetPartyCount 0x4009
	DecrementVar 0x4009 1
	SetVar 0x400A 0
	CMD_490 0x4009
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 0x4009 0x400A
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x400A 1
	JumpIf EQUAL Function#181
	TextPokeNickname 0 0x4009
	Message 54
	Message 51
	CloseMessage
	CloseTouchScreen
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#182
	Movement Overworld.15 Action#82
Jump Function#183

Function 175:
	Movement Overworld.12 Action#83
	WaitMovement
	Message 33
	CloseMessage
	Movement Overworld.12 Action#84
	WaitMovement
	Message 34
	CloseMessage
	Movement Overworld.12 Action#85
	WaitMovement
	RemoveOW Overworld.12
	SetFlag 573
	CommonScript 2068
	Release Following
	Movement Following Action#86
	WaitMovement
	Lock Following
	ReleaseAll
	SetVar 0x40E9 1
End

Function 176:
	WaitMovement
	Message 33
	CloseMessage
	Movement Overworld.12 Action#84
	WaitMovement
	Message 34
	CloseMessage
	Movement Overworld.12 Action#85
	WaitMovement
	RemoveOW Overworld.12
	SetFlag 573
	CommonScript 2068
	Release Following
	Movement Following Action#86
	WaitMovement
	Lock Following
	ReleaseAll
	SetVar 0x40E9 1
End

Function 177:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	PlayCry SPECIES_FARFETCHD 0
	Message 3
	CloseMessage
	Movement Overworld.0 Action#87
	WaitMovement
	RemoveOW Overworld.0
	Message 37
	WaitButton
	CloseMessage
	SetVar 0x4099 2
	SetVar 0x409B 2
	SetFlag 423
	SetFlag 125
	CheckFlag 126
	JumpIf EQUAL Function#184
	ClearFlag 467
	WaitTime 20 0x8004
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 117 0 15 65 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 5 0x8004
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 178:
	ReleaseAll
End

Function 179:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	PlayCry SPECIES_FARFETCHD 0
	Message 3
	CloseMessage
	Movement Overworld.2 Action#88
	WaitMovement
	RemoveOW Overworld.2
	Message 37
	WaitButton
	CloseMessage
	CheckFlag 125
	CallIf LESS Function#185
	SetVar 0x409A 2
	SetVar 0x409C 2
	SetVar 0x409D 2
	SetVar 0x409E 2
	SetFlag 424
	SetFlag 126
	CheckFlag 125
	JumpIf EQUAL Function#184
	ClearFlag 467
	WaitTime 20 0x8004
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 117 0 15 65 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 5 0x8004
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 180:
	GiveSpikyEaredPichu
	RemoveOW Overworld.14
	SetVar 0x412B 2
	PlaySound SEQ_ME_SHINKAOME
	Message 40
	WaitSound
	OpenTouchScreen
	Message 45
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#181
	CloseMessage
	GetPartyCount 0x4009
	DecrementVar 0x4009 1
	SetVar 0x400A 0
	CMD_490 0x4009
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonNickname 0x4009 0x400A
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x400A 1
	JumpIf EQUAL Function#181
	TextPokeNickname 0 0x4009
	Message 54
	Message 51
	CloseMessage
	CloseTouchScreen
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#182
	Movement Overworld.15 Action#82
Jump Function#183

Function 181:
	Message 51
	CloseMessage
	CloseTouchScreen
	CompareVarValue 0x4005 3
	JumpIf DIFFERENT Function#182
	Movement Overworld.15 Action#82
Jump Function#183

Function 182:
	Movement Overworld.15 Action#89
	WaitMovement
	RemoveOW Overworld.15
	SetFlag 668
Return

Function 183:
	WaitMovement
	RemoveOW Overworld.15
	SetFlag 668
Return

Function 184:
	ClearFlag 431
	AddOW Overworld.4
	ClearFlag 468
	WaitTime 20 0x8004
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 117 0 15 65 Up
	FadeScreen 6 1 1 0
	WaitFadeScreen
	WaitTime 5 0x8004
	Message 2
	WaitButton
	CloseMessage
	Movement Overworld.4 Action#90
	Movement Player Action#91
	WaitMovement
	CheckFlag 128
	JumpIf EQUAL Function#186
	Message 6
	SetVar 0x8004 420
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#187
	CommonScript 2033
	SetFlag 431
	SetFlag 429
	SetFlag 423
	SetFlag 424
	SetFlag 467
	SetFlag 468
	SetFlag 128
	ClearFlag 430
	ClearFlag 428
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 185:
	SetVar 0x4099 1
Return

Function 186:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 187:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
	WalkOnSpotSouth8 0x1
End

Action 2:
	WalkSouth8 0x1
	WalkEast8 0x2
	WalkSouth8 0x1
End

Action 3:
	EmoteExclamation 0x1
	WalkOnSpotNorth8 0x1
End

Action 4:
	JumpNorth8 0x1
End

Action 5:
	LockDir 0x1
	WalkSouth16 0x1
	ReleaseDir 0x1
End

Action 6:
	EmoteExclamation 0x1
End

Action 7:
	Delay8 0x2
	FaceNorth 0x1
End

Action 8:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 9:
	Delay8 0x1
	WalkOnSpotNorth8 0x1
End

Action 10:
	WalkOnSpotWest8 0x1
End

Action 11:
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotEast8 0x1
	Delay8 0x1
End

Action 12:
	WalkSouth8 0x1
	Delay8 0x1
End

Action 13:
	Delay8 0x1
	JumpOnSpotEast8 0x2
	LockDir 0x1
	JumpNorth8 0x1
	JumpSouth8 0x1
	ReleaseDir 0x1
End

Action 14:
	WalkOnSpotWest8 0x1
	EmoteExclamation 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
End

Action 15:
	WalkWest8 0x3
	Delay16 0x1
	JumpOnSpotWest8 0x2
End

Action 16:
	WalkEast8 0x3
End

Action 17:
	WalkEast8 0x3
End

Action 18:
	WalkWest8 0x4
	WalkNorth8 0x6
	WalkOnSpotSouth8 0x1
	Delay8 0x6
	WalkNorth8 0x5
End

Action 19:
	LockDir 0x1
	JumpSouth8 0x1
	ReleaseDir 0x1
	WalkOnSpotNorth8 0x1
	WalkWest8 0x3
	Delay8 0x1
	WalkOnSpotEast8 0x1
	Delay8 0x4
	WalkOnSpotNorth8 0x1
	JumpOnSpotNorth8 0x1
	WalkNorth8 0xA
End

Action 20:
	FaceWest 0x1
	EmoteExclamation 0x1
End

Action 21:
	WalkSouth8 0x1
	WalkEast8 0x3
	WalkSouth8 0x1
End

Action 22:
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
	FaceWest 0x1
	Delay2 0x1
	FaceNorth 0x1
	Delay2 0x1
	FaceEast 0x1
	Delay2 0x1
	FaceSouth 0x1
	Delay2 0x1
End

Action 23:
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 24:
	WalkEast8 0x1
	WalkNorth8 0x1
	FaceSouth 0x1
End

Action 25:
	WalkOnSpotEast8 0x1
End

Action 26:
	WalkOnSpotWest8 0x1
End

Action 27:
	EmoteExclamation 0x1
	WalkEast4 0x7
	FaceWest 0x1
End

Action 28:
	FaceSouth 0x1
	EmoteExclamation 0x1
End

Action 29:
	EmoteExclamation 0x1
	WalkEast4 0x8
	FaceWest 0x1
End

Action 30:
	FaceEast 0x1
	EmoteExclamation 0x1
End

Action 31:
	EmoteExclamation 0x1
	WalkSouth4 0x3
	FaceNorth 0x1
End

Action 32:
	EmoteExclamation 0x1
	WalkEast8 0x1
	WalkSouth4 0x2
	FaceNorth 0x1
End

Action 33:
	WalkWest8 0x2
	WalkSouth8 0x3
	WalkEast8 0x2
	FaceWest 0x1
	FaceEast 0x1
	FaceSouth 0x1
End

Action 34:
	LockDir 0x1
	JumpFarEast 0x1
	ReleaseDir 0x1
	JumpOnSpotSouth8 0x2
End

Action 35:
	EmoteExclamation 0x1
	Delay8 0x1
End

Action 36:
	WalkSouth4 0x7
	JumpOnSpotWest8 0x1
	WalkWest4 0x4
	WalkNorth4 0x4
	WalkEast4 0x4
	WalkSouth4 0x4
	WalkWest4 0x2
	FaceNorth 0x1
	JumpOnSpotNorth8 0x2
End

Action 37:
	Delay8 0x3
	FaceSouth 0x1
	Delay8 0x1
	WalkSouth8 0x2
	WalkOnSpotEast8 0x1
	Delay16 0x1
	WalkOnSpotWest8 0x1
	Delay16 0x1
	WalkOnSpotSouth8 0x1
End

Action 38:
	WalkEast8 0x1
	WalkSouth8 0x1
	FaceSouth 0x1
End

Action 39:
	LockDir 0x1
	JumpEast8 0x1
	ReleaseDir 0x1
	JumpOnSpotNorth8 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
End

Action 40:
	EmoteExclamation 0x1
	Delay8 0x1
	JumpOnSpotSouth8 0x2
End

Action 41:
	LockDir 0x1
	JumpSouth8 0x1
	ReleaseDir 0x1
	Delay16 0x1
	JumpOnSpotWest8 0x1
	WalkWest4 0x7
	WalkNorth4 0xD
	WalkEast8 0x1
End

Action 42:
	Delay16 0x2
	WalkSouth4 0x1
	WalkWest4 0x6
	JumpOnSpotNorth8 0x1
	WalkNorth4 0xD
	WalkWest4 0x1
End

Action 43:
	Delay16 0x5
	WalkSouth16 0xA
	WalkEast16 0x4
	WalkOnSpotEast8 0x1
End

Action 44:
	WalkSouth4 0xC
	WalkEast4 0x6
	WalkNorth4 0x4
	WalkWest4 0x3
	WalkSouth4 0x4
	WalkEast4 0x3
	LockDir 0x1
	JumpWest8 0x1
	ReleaseDir 0x1
	FaceSouth 0x6
	LockDir 0x1
	WalkWest16 0x1
	ReleaseDir 0x1
	FaceWest 0x6
	FaceNorth 0x6
	LockDir 0x1
	WalkEast16 0x1
	ReleaseDir 0x1
	FaceEast 0x6
	LockDir 0x1
	WalkWest16 0x1
	ReleaseDir 0x1
End

Action 45:
	WalkSouth4 0xD
	WalkEast4 0x7
	JumpOnSpotNorth8 0x1
	JumpOnSpotWest8 0x1
	Delay8 0x4
	LockDir 0x1
	JumpEast8 0x1
	ReleaseDir 0x1
	FaceSouth 0x6
	FaceEast 0x6
	FaceNorth 0x6
	FaceWest 0x6
	Delay32 0x1
	WalkWest8 0x1
End

Action 46:
	WalkOnSpotWest8 0x1
End

Action 47:
	WalkOnSpotNorth8 0x1
	Delay16 0x1
End

Action 48:
	WalkOnSpotSouth8 0x1
	Delay16 0x1
	EmoteExclamation 0x1
End

Action 49:
	Delay16 0x1
	WalkOnSpotNorth8 0x1
	Delay16 0x1
End

Action 50:
	WalkOnSpotSouth8 0x1
End

Action 51:
	JumpOnSpotNorth8 0x1
	JumpOnSpotEast8 0x1
End

Action 52:
	JumpWest8 0x1
	JumpOnSpotWest8 0x2
End

Action 53:
	WalkOnSpotWest8 0x1
End

Action 54:
	JumpOnSpotEast8 0x2
End

Action 55:
	JumpOnSpotNorth8 0x2
End

Action 56:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkSouth8 0x1
	WalkOnSpotWest8 0x1
End

Action 57:
	FaceWest 0x1
	LockDir 0x1
	WalkEast8 0x1
	ReleaseDir 0x1
End

Action 58:
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x3
	WalkOnSpotEast8 0x1
	JumpOnSpotEast8 0x3
End

Action 59:
	WalkNorth8 0x1
	WalkEast8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 60:
	WalkOnSpotSouth8 0x1
End

Action 61:
	WalkOnSpotEast8 0x1
End

Action 62:
	FaceNorth 0x1
	WalkOnSpotEast8 0x1
End

Action 63:
	FaceSouth 0x1
	FaceSouth 0x1
	JumpFarSouth 0x1
	LockDir 0x1
	JumpNorth8 0x1
	LockDir 0x1
End

Action 64:
	WalkSouth8 0xB
	WalkEast8 0x2
End

Action 65:
	WalkSouth8 0x8
	WalkOnSpotEast8 0x1
	WalkEast8 0x1
	LockDir 0x1
	WalkSouth8 0x1
	Delay8 0x1
	ReleaseDir 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkWest8 0x1
End

Action 66:
	WalkOnSpotWest8 0x1
End

Action 67:
	EmoteExclamation 0x1
	Delay8 0x1
	WalkOnSpotNorth8 0x1
	Delay8 0x1
	WalkOnSpotWest8 0x1
	Delay8 0x1
	WalkOnSpotSouth8 0x1
	Delay8 0x1
End

Action 68:
	Delay16 0x1
	WalkEast8 0x2
	WalkNorth8 0x2
	WalkOnSpotEast8 0x1
End

Action 69:
	WalkNorth8 0x1
	WalkOnSpotWest8 0x1
End

Action 70:
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x3
	WalkOnSpotEast8 0x1
End

Action 71:
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x3
	WalkOnSpotEast8 0x1
	JumpOnSpotEast8 0x3
End

Action 72:
	WalkNorth8 0x1
	WalkWest8 0x1
	WalkNorth8 0x3
	WalkOnSpotSouth8 0x1
End

Action 73:
	WalkOnSpotSouth8 0x1
End

Action 74:
	EmoteExclamation 0x1
	WalkNorth4 0xA
	FaceSouth 0x1
End

Action 75:
	EmoteExclamation 0x1
	WalkWest4 0x7
	FaceEast 0x1
End

Action 76:
	EmoteExclamation 0x1
	WalkWest4 0x8
	FaceEast 0x1
End

Action 77:
	WalkSouth8 0x1
	WalkOnSpotEast8 0x1
End

Action 78:
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x1
	WalkNorth8 0x2
	WalkWest8 0x3
	WalkOnSpotEast8 0x1
End

Action 79:
	WalkOnSpotWest8 0x1
End

Action 80:
	WalkEast8 0x1
	WalkNorth8 0x2
	WalkOnSpotWest8 0x1
End

Action 81:
	WalkSouth8 0x1
	WalkOnSpotWest8 0x1
End

Action 82:
	WalkSouth16 0x2
	WalkWest16 0x4
	WalkNorth16 0xC
End

Action 83:
	WalkWest8 0x1
End

Action 84:
	WalkOnSpotSouth8 0x1
End

Action 85:
	WalkWest8 0x2
	WalkNorth8 0x2
	WalkWest8 0x6
End

Action 86:
	WalkEast8 0x3
	WalkSouth8 0x2
	WalkEast8 0x1
	WalkSouth8 0x1
	WalkOnSpotEast8 0x1
End

Action 87:
	WalkOnSpotSouth4 0x5
End

Action 88:
	WalkOnSpotEast4 0x5
End

Action 89:
	WalkOnSpotEast8 0x1
	Delay16 0x1
	WalkWest16 0x4
	WalkNorth16 0xA
End

Action 90:
	WalkNorth8 0xA
	WalkEast8 0x3
End

Action 91:
	Delay8 0xC
	FaceWest 0x1
End

