/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0185
 * Generated: 9/2/2026 12:10:04 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 280
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
