/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0752
 * Generated: 9/2/2026 12:10:08 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#1
	CheckBadge 8 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	TrainerBattle TRAINER_BROCK_253 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 8
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JERRY_308
	SetTrainerFlag TRAINER_EDWIN_685
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	TextPlayerName 0
	GenderMessage 3 4
Jump Function#4

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 8 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#5
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 8 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#6
	Message 8
Jump Function#7

Script 4:
	CheckPokeGearRematch 33 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#8
	CheckPokegearNumberRegistered 33 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#9
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#10
Jump Function#11

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 8 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	AdrsValueSet 0x20436D4 16
	FlashAnimation
	AdrsValueSet 0x20436D4 0
	TrainerBattle TRAINER_BROCK_720 TRAINER_BROCK_720 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 8
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JERRY_308
	SetTrainerFlag TRAINER_EDWIN_685
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	TextPlayerName 0
	GenderMessage 3 4
Jump Function#4

Function 2:
	CheckFlag 383
	JumpIf LESS Function#4
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	SetVar 0x8004 407
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CommonScript 2033
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#13
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#14
	SetFlag 383
	CheckFlag 383
	JumpIf LESS Function#4
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	SetFlag 756
End

Function 9:
	GetHour 0x4000
	CompareVarValue 0x4000 17
	JumpIf DIFFERENT Function#15
	SetFlag 756
Jump Function#16

Function 10:
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#17
	SetFlag 756
Jump Function#18

Function 11:
	ClearFlag 756
End

Function 12:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 13:
	IncrementVar 0x416F 15
	SetFlag 383
	CheckFlag 383
	JumpIf LESS Function#4
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	IncrementVar 0x416F 10
	SetFlag 383
	CheckFlag 383
	JumpIf LESS Function#4
	TextPlayerName 0
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#19
	SetFlag 756
Jump Function#16

Function 16:
End

Function 17:
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#20
	SetFlag 756
Jump Function#18

Function 18:
End

Function 19:
	CompareVarValue 0x4000 19
	JumpIf DIFFERENT Function#21
	SetFlag 756
Jump Function#16

Function 20:
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#22
	SetFlag 756
Jump Function#18

Function 21:
Jump Function#11

Function 22:
Jump Function#11

//===== ACTIONS =====//
