/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0760
 * Generated: 9/2/2026 12:10:08 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#1
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 8
	CloseMessage
	TrainerBattle TRAINER_MISTY_254 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 9
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_DIANA_297
	SetTrainerFlag TRAINER_BRIANA_298
	SetTrainerFlag TRAINER_JOY_678
	SetTrainerFlag TRAINER_PARKER_676
	SetTrainerFlag TRAINER_EDDIE_677
	Message 9
	TextPlayerName 0
	Message 10
	PlaySound SEQ_ME_BADGE
	WaitSound
	CheckFlag 333
	CallIf EQUAL Function#4
	TextPlayerName 0
	Message 11
Jump Function#5

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4088 2
	JumpIf DIFFERENT Function#7
	CheckBadge 9 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#8
	Message 6
Jump Function#9

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CompareVarValue 0x4088 2
	JumpIf DIFFERENT Function#10
	CheckBadge 9 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#11
	Message 6
Jump Function#12

Script 5:
	MecScript
	LockAll
	StopMusic 1065
	PlayMusic SEQ_GS_EYE_ROCKET
	Movement Overworld.7 Action#1
	WaitMovement
	PlayFanfare SEQ_SE_DP_WALL_HIT2
	Message 0
	Movement Overworld.7 Action#2
	WaitMovement
	Message 1
	Movement Overworld.7 Action#3
	WaitMovement
	Message 2
	Movement Overworld.7 Action#4
	WaitMovement
	Message 3
	CloseMessage
	CheckPokemonAlive 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#13
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	TextPlayerName 0
	Message 16
	SetVar 0x8004 481
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#15
	CommonScript 2008
	RemoveOW Overworld.8
	RemoveOW Overworld.9
	SetFlag 599
	SetVar 0x4087 4
	CloseMessage
	ReleaseAll
End

Script 7:
	CMD_814
	CheckFlag 599
	JumpIf EQUAL Function#16
	VanishOverworld Overworld.8
	VanishOverworld Overworld.9
End

Script 8:
	CheckPokeGearRematch 29 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#17
	CheckBadge 15 0x4000
	CompareVarValue 0x4000 0
	JumpIf EQUAL Function#18
	CompareVarValue 0x4089 1
	JumpIf EQUAL Function#19
	CompareVarValue 0x4089 2
	JumpIf EQUAL Function#19
	CheckPokegearNumberRegistered 29 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#20
	GetHour 0x4000
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#21
	SetFlag 595
Jump Function#22

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 9 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 8
	CloseMessage
	AdrsValueSet 0x20436D4 15
	FlashAnimation
	AdrsValueSet 0x20436D4 0
	TrainerBattle TRAINER_MISTY_721 TRAINER_MISTY_721 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 9
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_DIANA_297
	SetTrainerFlag TRAINER_BRIANA_298
	SetTrainerFlag TRAINER_JOY_678
	SetTrainerFlag TRAINER_PARKER_676
	SetTrainerFlag TRAINER_EDDIE_677
	Message 9
	TextPlayerName 0
	Message 10
	PlaySound SEQ_ME_BADGE
	WaitSound
	CheckFlag 333
	CallIf EQUAL Function#4
	TextPlayerName 0
	Message 11
Jump Function#5

Function 2:
	CheckFlag 384
	JumpIf LESS Function#5
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	ClearFlag 673
	SetVar 0x4089 1
Return

Function 5:
	SetVar 0x8004 330
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#23
	CommonScript 2033
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#24
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#25
	SetFlag 384
	TextPlayerName 0
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 4
Jump Function#26

Function 8:
	Message 7
Jump Function#26

Function 9:
Jump Function#26

Function 10:
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 7
Jump Function#26

Function 12:
Jump Function#26

Function 13:
	Movement Overworld.7 Action#5
	Movement Player Action#6
	WaitMovement
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.7
	WaitFanfare SEQ_SE_DP_KAIDAN2
	StopMusic 1112
	PlayMusic SEQ_GS_GYM
	SetFlag 596
	ClearFlag 597
	ClearFlag 598
	ClearFlag 777
	SetVar 0x411C 2
	SetVar 0x4087 1
	SetVar 0x4088 1
	ReleaseAll
End

Function 14:
	Movement Overworld.7 Action#5
	Movement Player Action#6
	Movement Following Action#7
	WaitMovement
Jump Function#27

Function 15:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 16:
End

Function 17:
	SetFlag 595
End

Function 18:
End

Function 19:
	ClearFlag 595
End

Function 20:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#28
	SetFlag 595
Jump Function#29

Function 21:
	CompareVarValue 0x4000 17
	JumpIf DIFFERENT Function#30
	SetFlag 595
Jump Function#22

Function 22:
End

Function 23:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 24:
	IncrementVar 0x416F 15
	SetFlag 384
	TextPlayerName 0
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 25:
	IncrementVar 0x416F 10
	SetFlag 384
	TextPlayerName 0
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 26:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 27:
	PlayFanfare SEQ_SE_DP_KAIDAN2
	RemoveOW Overworld.7
	WaitFanfare SEQ_SE_DP_KAIDAN2
	StopMusic 1112
	PlayMusic SEQ_GS_GYM
	SetFlag 596
	ClearFlag 597
	ClearFlag 598
	ClearFlag 777
	SetVar 0x411C 2
	SetVar 0x4087 1
	SetVar 0x4088 1
	ReleaseAll
End

Function 28:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#31
	SetFlag 595
Jump Function#29

Function 29:
End

Function 30:
	ClearFlag 595
End

Function 31:
	ClearFlag 595
End

//===== ACTIONS =====//
Action 1:
	WalkSouth2 0x5
End

Action 2:
	LockDir 0x1
	JumpFarNorth 0x1
	Delay8 0x2
	WalkSouth4 0x2
End

Action 3:
	EmoteExclamation 0x1
	LockDir 0x1
	WalkNorth8 0x2
End

Action 4:
	WalkSouth8 0x2
End

Action 5:
	WalkSouth4 0x1
End

Action 6:
	WalkWest4 0x1
	FaceEast 0x1
End

Action 7:
	WalkWest4 0x1
End

