/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0786
 * Generated: 9/2/2026 12:10:08 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#1
	CheckBadge 11 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	TrainerBattle TRAINER_ERIKA_256 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 11
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JO_AND_ZOE_326
	SetTrainerFlag TRAINER_MICHELLE_356
	SetTrainerFlag TRAINER_TANYA_336
	SetTrainerFlag TRAINER_JULIA_346
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#4

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 11 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#5
	Message 5
Jump Function#6

Script 3:
	CheckPokeGearRematch 28 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#7
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#8
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#9
Jump Function#10

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 11 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	AdrsValueSet 0x20436D4 20
	FlashAnimation
	AdrsValueSet 0x20436D4 0
	TrainerBattle TRAINER_ERIKA_723 TRAINER_ERIKA_723 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	GiveBadge 11
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_JO_AND_ZOE_326
	SetTrainerFlag TRAINER_MICHELLE_356
	SetTrainerFlag TRAINER_TANYA_336
	SetTrainerFlag TRAINER_JULIA_346
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#4

Function 2:
	CheckFlag 292
	JumpIf LESS Function#4
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	SetVar 0x8004 346
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#11
	CommonScript 2033
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#13
	SetFlag 292
	CheckFlag 292
	JumpIf LESS Function#4
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	SetFlag 754
End

Function 8:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 1
	JumpIf DIFFERENT Function#14
	SetFlag 754
Jump Function#15

Function 9:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#16
Jump Function#17

Function 10:
	ClearFlag 754
End

Function 11:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 12:
	IncrementVar 0x416F 15
	SetFlag 292
	CheckFlag 292
	JumpIf LESS Function#4
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 13:
	IncrementVar 0x416F 10
	SetFlag 292
	CheckFlag 292
	JumpIf LESS Function#4
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
Jump Function#10

Function 15:
End

Function 16:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#18
Jump Function#17

Function 17:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#19
	SetFlag 754
Jump Function#20

Function 18:
Jump Function#10

Function 19:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#21
	SetFlag 754
Jump Function#20

Function 20:
End

Function 21:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#22
	SetFlag 754
Jump Function#20

Function 22:
Jump Function#10

//===== ACTIONS =====//
