/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0809
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	FuchsiaGymInit
	CheckPokeGearRematch 26 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#1
	CheckPokegearNumberRegistered 26 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#2
	CheckBadge 12 0x4002
	CompareVarValue 0x4002 0
	JumpIf DIFFERENT Function#3
Jump Function#4

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#5
	CheckBadge 12 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 0
	CloseMessage
	SetVar 0x400B 111
	TrainerBattle TRAINER_JANINE_257 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	SetVar 0x400B 0
	GiveBadge 12
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_CINDY_083
	SetTrainerFlag TRAINER_BARRY_084
	SetTrainerFlag TRAINER_LINDA_136
	SetTrainerFlag TRAINER_ALICE_183
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#8

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 12 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#9
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckTrainerFlag TRAINER_LINDA_136
	JumpIf EQUAL Function#10
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#11
	Movement Overworld.8 Action#1
Jump Function#12

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckTrainerFlag TRAINER_BARRY_084
	JumpIf EQUAL Function#13
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#14
	Movement Overworld.7 Action#1
Jump Function#15

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckTrainerFlag TRAINER_ALICE_183
	JumpIf EQUAL Function#16
	Message 11
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#17
	Movement Overworld.9 Action#1
Jump Function#18

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckTrainerFlag TRAINER_CINDY_083
	JumpIf EQUAL Function#19
	Message 14
	CloseMessage
	GetPlayerDirection 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#20
	Movement Overworld.6 Action#1
Jump Function#21

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 12 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#22
	Message 17
Jump Function#23

Script 9:
	CompareVarValue 0x400B 111
	JumpIf DIFFERENT Function#24
	CheckTrainerFlag TRAINER_LINDA_136
	CallIf LESS Function#25
	CheckTrainerFlag TRAINER_BARRY_084
	CallIf LESS Function#26
	CheckTrainerFlag TRAINER_ALICE_183
	CallIf LESS Function#27
	CheckTrainerFlag TRAINER_CINDY_083
	CallIf LESS Function#28
End

//===== FUNCTIONS =====//
Function 1:
	SetFlag 755
End

Function 2:
	GetHour 0x4000
	CompareVarValue 0x4000 18
	JumpIf DIFFERENT Function#29
	SetFlag 755
Jump Function#30

Function 3:
Jump Function#31

Function 4:
	ClearFlag 755
End

Function 5:
	CheckBadge 12 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 0
	CloseMessage
	SetVar 0x400B 111
	TrainerBattle TRAINER_JANINE_724 TRAINER_JANINE_724 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	SetVar 0x400B 0
	GiveBadge 12
	IncrementVar 0x4135 1
	AddTrainerScore 22
	SetTrainerFlag TRAINER_CINDY_083
	SetTrainerFlag TRAINER_BARRY_084
	SetTrainerFlag TRAINER_LINDA_136
	SetTrainerFlag TRAINER_ALICE_183
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
Jump Function#8

Function 6:
	CheckFlag 301
	JumpIf LESS Function#8
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	LostBattle
	ReleaseAll
End

Function 8:
	SetVar 0x8004 411
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#32
	CommonScript 2033
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#33
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#34
	SetFlag 301
	CheckFlag 301
	JumpIf LESS Function#8
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#35
	Movement Overworld.8 Action#2
Jump Function#12

Function 12:
	WaitMovement
	ClearFlag 614
	AddOW Overworld.1
	SetFlag 618
	RemoveOW Overworld.8
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#36
	Movement Overworld.1 Action#3
Jump Function#37

Function 13:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#38
	Movement Overworld.7 Action#2
Jump Function#15

Function 15:
	WaitMovement
	ClearFlag 615
	AddOW Overworld.5
	SetFlag 619
	RemoveOW Overworld.7
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#39
	Movement Overworld.5 Action#3
Jump Function#40

Function 16:
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#41
	Movement Overworld.9 Action#2
Jump Function#18

Function 18:
	WaitMovement
	ClearFlag 616
	AddOW Overworld.4
	SetFlag 620
	RemoveOW Overworld.9
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#42
	Movement Overworld.4 Action#3
Jump Function#43

Function 19:
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#44
	Movement Overworld.6 Action#2
Jump Function#21

Function 21:
	WaitMovement
	ClearFlag 617
	AddOW Overworld.0
	SetFlag 621
	RemoveOW Overworld.6
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#45
	Movement Overworld.0 Action#3
Jump Function#46

Function 22:
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 23:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 24:
End

Function 25:
	ClearFlag 614
	AddOW Overworld.1
	SetFlag 618
	RemoveOW Overworld.8
Return

Function 26:
	ClearFlag 615
	AddOW Overworld.5
	SetFlag 619
	RemoveOW Overworld.7
Return

Function 27:
	ClearFlag 616
	AddOW Overworld.4
	SetFlag 620
	RemoveOW Overworld.9
Return

Function 28:
	ClearFlag 617
	AddOW Overworld.0
	SetFlag 621
	RemoveOW Overworld.6
Return

Function 29:
	CompareVarValue 0x4000 19
	JumpIf DIFFERENT Function#47
	SetFlag 755
Jump Function#30

Function 30:
End

Function 31:
	GetHour 0x4000
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#48
	SetFlag 755
Jump Function#49

Function 32:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 33:
	IncrementVar 0x416F 15
	SetFlag 301
	CheckFlag 301
	JumpIf LESS Function#8
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 34:
	IncrementVar 0x416F 10
	SetFlag 301
	CheckFlag 301
	JumpIf LESS Function#8
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 35:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#50
	Movement Overworld.8 Action#4
Jump Function#12

Function 36:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#51
	Movement Overworld.1 Action#5
Jump Function#37

Function 37:
	WaitMovement
	Message 7
	CloseMessage
	TrainerBattle TRAINER_LINDA_136 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#52
	SetTrainerFlag TRAINER_LINDA_136
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#53
	Movement Overworld.7 Action#4
Jump Function#15

Function 39:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#54
	Movement Overworld.5 Action#5
Jump Function#40

Function 40:
	WaitMovement
	Message 9
	CloseMessage
	TrainerBattle TRAINER_BARRY_084 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#55
	SetTrainerFlag TRAINER_BARRY_084
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 41:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#56
	Movement Overworld.9 Action#4
Jump Function#18

Function 42:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#57
	Movement Overworld.4 Action#5
Jump Function#43

Function 43:
	WaitMovement
	Message 12
	CloseMessage
	TrainerBattle TRAINER_ALICE_183 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#58
	SetTrainerFlag TRAINER_ALICE_183
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 44:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#59
	Movement Overworld.6 Action#4
Jump Function#21

Function 45:
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#60
	Movement Overworld.0 Action#5
Jump Function#46

Function 46:
	WaitMovement
	Message 15
	CloseMessage
	TrainerBattle TRAINER_CINDY_083 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#61
	SetTrainerFlag TRAINER_CINDY_083
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 47:
Jump Function#4

Function 48:
	CompareVarValue 0x4000 17
	JumpIf DIFFERENT Function#62
	SetFlag 755
Jump Function#49

Function 49:
End

Function 50:
	Movement Overworld.8 Action#6
	WaitMovement
	ClearFlag 614
	AddOW Overworld.1
	SetFlag 618
	RemoveOW Overworld.8
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#36
	Movement Overworld.1 Action#3
Jump Function#37

Function 51:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#63
	Movement Overworld.1 Action#7
Jump Function#37

Function 52:
	LostBattle
	ReleaseAll
	SetFlag 614
	ClearFlag 618
End

Function 53:
	Movement Overworld.7 Action#6
	WaitMovement
	ClearFlag 615
	AddOW Overworld.5
	SetFlag 619
	RemoveOW Overworld.7
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#39
	Movement Overworld.5 Action#3
Jump Function#40

Function 54:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#64
	Movement Overworld.5 Action#7
Jump Function#40

Function 55:
	LostBattle
	ReleaseAll
	SetFlag 615
	ClearFlag 619
End

Function 56:
	Movement Overworld.9 Action#6
	WaitMovement
	ClearFlag 616
	AddOW Overworld.4
	SetFlag 620
	RemoveOW Overworld.9
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#42
	Movement Overworld.4 Action#3
Jump Function#43

Function 57:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#65
	Movement Overworld.4 Action#7
Jump Function#43

Function 58:
	LostBattle
	ReleaseAll
	SetFlag 616
	ClearFlag 620
End

Function 59:
	Movement Overworld.6 Action#6
	WaitMovement
	ClearFlag 617
	AddOW Overworld.0
	SetFlag 621
	RemoveOW Overworld.6
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#45
	Movement Overworld.0 Action#3
Jump Function#46

Function 60:
	CompareVarValue 0x800C 2
	JumpIf DIFFERENT Function#66
	Movement Overworld.0 Action#7
Jump Function#46

Function 61:
	LostBattle
	ReleaseAll
	SetFlag 617
	ClearFlag 621
End

Function 62:
Jump Function#4

Function 63:
	Movement Overworld.1 Action#8
	WaitMovement
	Message 7
	CloseMessage
	TrainerBattle TRAINER_LINDA_136 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#52
	SetTrainerFlag TRAINER_LINDA_136
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 64:
	Movement Overworld.5 Action#8
	WaitMovement
	Message 9
	CloseMessage
	TrainerBattle TRAINER_BARRY_084 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#55
	SetTrainerFlag TRAINER_BARRY_084
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 65:
	Movement Overworld.4 Action#8
	WaitMovement
	Message 12
	CloseMessage
	TrainerBattle TRAINER_ALICE_183 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#58
	SetTrainerFlag TRAINER_ALICE_183
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 66:
	Movement Overworld.0 Action#8
	WaitMovement
	Message 15
	CloseMessage
	TrainerBattle TRAINER_CINDY_083 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#61
	SetTrainerFlag TRAINER_CINDY_083
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
End

Action 2:
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
End

Action 3:
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
End

Action 4:
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
End

Action 5:
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
End

Action 6:
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
End

Action 7:
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
End

Action 8:
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
	FaceNorth 0x1
	FaceEast 0x1
	FaceSouth 0x1
	FaceWest 0x1
End

