/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0846
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_PC_ON
	TextPlayerName 0
	Message 0
	CloseMessage
	CountMail 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	MailScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	Message 3
	WaitButton
	Message 4
	OpenTouchScreen
	MultiTouchLocalText 1 1 0 1 0x800C
	CreateMultiTouchBox 5 255 0
	CreateMultiTouchBox 6 255 1
	CreateMultiTouchBox 10 255 2
	CreateMultiTouchBox 8 255 3
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#2
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#4
Jump Function#5

Script 4:
	ClearFlag 2550
End

Script 5:
	SetFlag 2550
	SetVar 0x4169 1
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	SetVar 0x406A 1
	Message 9
	WaitButton
Jump Function#5

Function 3:
	SetVar 0x406A 2
	Message 9
	WaitButton
Jump Function#5

Function 4:
	SetVar 0x406A 3
	Message 9
	WaitButton
Jump Function#5

Function 5:
	CheckFlag 2404
	JumpIf EQUAL Function#6
Jump Function#7

Function 6:
	SetVar 0x416F 100
Jump Function#7

Function 7:
	CloseTouchScreen
	Message 7
	SetFlag 2564
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
