/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0855
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	Movement Overworld.0 Action#1
	WaitMovement
	LockAll
	Message 0
	WaitButton
	FadeScreen 6 1 0 0
	WaitFadeScreen
	SetOWPosition Overworld.0 5 0 5 Right
	SetOWPosition Player 8 0 5 Left
	SetOWPosition Following 8 0 6 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 1
	SetVar 0x416D 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	CheckFlag 2404
	JumpIf EQUAL Function#1
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	LockAll
	FacePlayer
	Message 2
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
Jump Function#3

Function 2:
	Message 3
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 3:
	Message 4
	WaitButton
	CloseMessage
	CloseTouchScreen
	FadeScreen 6 1 0 0
	WaitFadeScreen
	Warp 523 0 8 5 Left
	FadeScreen 6 1 1 0
	WaitFadeScreen
Jump Function#4

Function 4:
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	FaceSouth 0x1
	EmoteExclamation 0x1
	WalkEast8 0x1
	WalkSouth8 0x2
End

