/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0907
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PartyLegalCheck 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	CheckFlag 274
	JumpIf EQUAL Function#2
	SetFlag 274
	Message 0
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 131 255 0
	CreateMultiTouchBox 130 255 1
	CreateMultiTouchBox 132 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#5
Jump Function#5

Script 2:
	CompareVarValue 0x4133 6
	CallIf EQUAL Function#6
End

Script 3:
	MecScript
	LockAll
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 8
	JumpIf EQUAL Function#7
Jump Function#8

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 13
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 10:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 16
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 11:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 12:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x8005 3
Jump Function#9

Script 13:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	SetVar 0x8005 4
Jump Function#10

Script 14:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 27
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 15:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 16:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	PartyLegalCheck 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	SetVar 0x8000 0
	GetPartyPokemonID 0x8000 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	TextPartyPokemon 0 0
	Message 18
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#13
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
End

Script 17:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 24
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CloseMessage
	CMD_681 0x8004
	CompareVarValue 0x8004 0
	JumpIf EQUAL Function#15
	Message 25
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 18:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 36
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 19:
	Lock Player
	Lock Overworld.13
	FacePlayer
	PlayFanfare SEQ_SE_CONFIRM
	Message 37
	CloseMessage
	Message 38
	ShowMoney 20 2
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	CallIf EQUAL Function#16
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#17
	Message 39
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PartyPokemonTradeScreen
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#18
	TextPokemon 1 0x800C 0 0
	Message 40
	YesNoBox 0x8004
	CloseMessage
	CompareVarValue 0x8004 0
	JumpIf DIFFERENT Function#18
	DeletePartyPokemon 0x800C
	GetRandom 0x8004 1024
	IncrementVar 0x8004 1
	CompareVarValue 0x8004 494
	CallIf GREATER/EQUAL Function#19
	Message 41
	CloseMessage
	PlayFanfare SEQ_SE_PL_BREC03
	WaitFanfare SEQ_SE_PL_BREC03
	PlayFanfare SEQ_SE_GS_KIRAKIRA
	WaitFanfare SEQ_SE_GS_KIRAKIRA
	GivePokemon 0x8004 28 ITEM_NONE 0 0 0x8007
	Call Function#20
	PlaySound SEQ_ME_POKEGET
	PlayCry 0x8004 0
	TextPlayerName 0
	TextPokemon 1 0x8004 0 0
	Message 42
	WaitSound
	WaitCry
	CloseMessage
	HidePokemonPic
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	CommonScript 0x2338
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 1
Jump Function#21

Function 3:
	CountPartyBornPokemon 0x800C
	CompareVarValue 0x800C 2
	JumpIf LESS Function#22
Jump Function#23

Function 4:
	Message 2
Jump Function#24

Function 5:
	SetVar 0x4133 0
	CloseTouchScreen
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	VanishOverworld Player
Return

Function 7:
	CompareVarValue 0x4001 2
	JumpIf EQUAL Function#25
Jump Function#8

Function 8:
	SetVar 0x4133 0
	ReleaseAll
End

Function 9:
	Message 31
	OpenTouchScreen
	MultiTouchLocalText 21 11 0 1 0x800C
	CreateMultiTouchBox 33 255 0
	CreateMultiTouchBox 34 255 1
	CreateMultiTouchBox 35 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#26
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#27
Jump Function#28

Function 10:
	Message 29
	OpenTouchScreen
	MultiTouchLocalText 21 11 0 1 0x800C
	CreateMultiTouchBox 33 255 0
	CreateMultiTouchBox 34 255 1
	CreateMultiTouchBox 35 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#29
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#30
Jump Function#31

Function 11:
	Message 23
Jump Function#32

Function 12:
	Message 19
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#13
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#33
End

Function 13:
	SetFavoriteMon
	Message 20
Jump Function#32

Function 14:
	TextPartyPokemon 0 0
	Message 21
Jump Function#32

Function 15:
	Message 26
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	CompareMoney 0x8008 0x2710
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#34
	TakeMoney 0x2710
	UpdateMoney
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	HideMoney
Return

Function 17:
	HideMoney
	Message 43
	CloseMessage
	ReleaseAll
End

Function 18:
	GiveMoney 0x2710
	Message 44
	PlayFanfare SEQ_SE_DP_REGI
	WaitFanfare SEQ_SE_DP_REGI
	CloseMessage
	ReleaseAll
End

Function 19:
	IncrementVar 0x8004 50
Return

Function 20:
	GetPartyCount 0x8008
	DecrementVar 0x8008 1
	GetPokemonGender 0x8008 0x8006
	CompareVarValue 0x8006 0
	CallIf EQUAL Function#35
	CompareVarValue 0x8006 1
	CallIf EQUAL Function#36
	CompareVarValue 0x8006 2
	CallIf EQUAL Function#35
Return

Function 21:
	OpenTouchScreen
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 131 255 0
	CreateMultiTouchBox 130 255 1
	CreateMultiTouchBox 132 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#5
Jump Function#5

Function 22:
	Message 9
	WaitButton
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 23:
	GetPartyCount 0x800C
	CompareVarValue 0x800C 6
	JumpIf EQUAL Function#37
Jump Function#38

Function 24:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 133 255 0
	CreateMultiTouchBox 134 255 1
	CreateMultiTouchBox 135 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#39
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#40
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#41
Jump Function#41

Function 25:
	Call Function#42
	SetVar 0x4133 0
	ReleaseAll
End

Function 26:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#43
	CloseMessage
	CMD_815 0
	CommonScript 2046
	ReleaseAll
End

Function 27:
	Message 32
Jump Function#9

Function 28:
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 29:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#44
	CloseMessage
	CMD_815 0
	CommonScript 2046
	ReleaseAll
End

Function 30:
	Message 30
Jump Function#10

Function 31:
	CloseTouchScreen
	CloseMessage
	ReleaseAll
End

Function 32:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 33:
	Message 22
Jump Function#32

Function 34:
	Message 49
	CloseMessage
	HideMoney
	ReleaseAll
End

Function 35:
	ShowPokemonPic 0x8004 0
Return

Function 36:
	ShowPokemonPic 0x8004 1
Return

Function 37:
	CountPCFreeSpace 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#45
Jump Function#38

Function 38:
	CommonScript 2006
	SetVarFromVariable 0x800C 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#46
	CloseTouchScreen
	HealPokemon
	SetVar 0x4133 6
	Message 7
	CloseMessage
	Movement Player Action#1
	WaitMovement
	DoorAnimation 0 0 8 4 77
	Call Function#47
	Movement Player Action#2
	WaitMovement
	Call Function#48
	DoorAnimation 0 0 8 2 77
	Call Function#47
	Movement Player Action#3
	WaitMovement
	VanishOverworld Player
	Movement Player Action#4
	WaitMovement
	Call Function#48
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_579
	CMD_815 0
	InitWFC 0x800C
	SetVarFromVariable 0x8004 0x800C
	StoreGTSStatus 0x8004 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#49
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Call Function#42
	ReleaseAll
End

Function 39:
	Message 3
Jump Function#24

Function 40:
	Message 4
Jump Function#24

Function 41:
	Message 5
Jump Function#50

Function 42:
	DoorAnimation 0 0 8 2 77
	Call Function#47
	UnvanishOverworld Player
	Movement Player Action#5
	WaitMovement
	Call Function#48
	DoorAnimation 0 0 8 4 77
	Call Function#47
	Movement Player Action#6
	WaitMovement
	Call Function#48
	SetVar 0x4133 0
Return

Function 43:
	CloseMessage
	ReleaseAll
End

Function 44:
	CloseMessage
	ReleaseAll
End

Function 45:
	CloseTouchScreen
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 46:
	SetVar 0x4133 0
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 47:
	OpenDoor 77
	WaitDoor 77
Return

Function 48:
	CloseDoor 77
	WaitDoor 77
	FreeDoor 77
Return

Function 49:
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Call Function#42
Jump Function#46

Function 50:
	MultiTouchStandardText 1 1 0 1 0x800C
	CreateMultiTouchBox 131 255 0
	CreateMultiTouchBox 130 255 1
	CreateMultiTouchBox 132 255 2
	CloseMultiTouch
	SetVarFromVariable 0x8008 0x800C
	CompareVarValue 0x8008 0
	JumpIf EQUAL Function#3
	CompareVarValue 0x8008 1
	JumpIf EQUAL Function#4
	CompareVarValue 0x8008 2
	JumpIf EQUAL Function#5
Jump Function#5

//===== ACTIONS =====//
Action 1:
	WalkEast8 0x1
	WalkOnSpotNorth8 0x1
End

Action 2:
	WalkNorth8 0x2
End

Action 3:
	WalkNorth8 0x1
End

Action 4:
	FaceSouth 0x1
End

Action 5:
	WalkSouth8 0x1
End

Action 6:
	WalkSouth8 0x2
End

