/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0913
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#1
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	TrainerBattle TRAINER_JASMINE_033 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	GiveBadge 5
	AddTrainerScore 22
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#4
	SetVar 0x4077 1
	Message 3
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#7
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Script 2:
	MecScript
	LockAll
	Movement Overworld.2 Action#1
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#8
	Movement Overworld.2 Action#2
Jump Function#9

Script 3:
	MecScript
	LockAll
	Movement Overworld.1 Action#1
	WaitMovement
	GetPlayerPosition 0x4000 0x4001
	CompareVarValue 0x4000 5
	JumpIf DIFFERENT Function#10
	Movement Overworld.1 Action#3
Jump Function#11

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#12
	Message 20
Jump Function#13

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf DIFFERENT Function#14
	Message 22
Jump Function#15

Script 6:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#16
	CompareVarValue 0x410E 0
	JumpIf DIFFERENT Function#17
	Message 16
Jump Function#18

Script 7:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 5 0x800C
	TextPlayerName 0
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#19
	Message 23
Jump Function#20

Script 8:
	CheckPokeGearRematch 38 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#21
	CheckFlag 2404
	JumpIf LESS Function#22
	ClearFlag 473
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#23
	GetHour 0x4000
	CompareVarValue 0x4000 13
	JumpIf DIFFERENT Function#24
	SetFlag 473
Jump Function#25

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 5 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	AdrsValueSet 0x20436D4 16
	FlashAnimation
	AdrsValueSet 0x20436D4 0
	TrainerBattle TRAINER_JASMINE_717 TRAINER_JASMINE_717 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	GiveBadge 5
	AddTrainerScore 22
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#4
	SetVar 0x4077 1
	Message 3
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#7
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 2:
	CheckFlag 194
	JumpIf LESS Function#26
	CheckPokegearNumberRegistered 38 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#27
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	Message 3
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 5:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 6:
	IncrementVar 0x416F 15
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 7:
	IncrementVar 0x416F 10
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 8:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#28
	Movement Overworld.2 Action#4
Jump Function#9

Function 9:
	Movement Player Action#5
	WaitMovement
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#29
	SetVar 0x410E 2
End

Function 10:
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#30
	Movement Overworld.1 Action#6
Jump Function#11

Function 11:
	Movement Player Action#7
	WaitMovement
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#31
	SetVar 0x410E 3
End

Function 12:
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#32
	SetVar 0x410E 2
End

Function 13:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#32
	SetVar 0x410E 2
End

Function 14:
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#33
	SetVar 0x410E 3
End

Function 15:
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#33
	SetVar 0x410E 3
End

Function 16:
	Message 18
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 17:
	Message 17
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 18:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 19:
	Message 24
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 20:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 21:
	SetFlag 473
End

Function 22:
End

Function 23:
	GetHour 0x4000
	CompareVarValue 0x4000 12
	JumpIf DIFFERENT Function#34
	SetFlag 473
Jump Function#35

Function 24:
Jump Function#36

Function 25:
End

Function 26:
	SetVar 0x8004 350
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 194
End

Function 27:
	CheckFlag 358
	JumpIf EQUAL Function#37
	CompareVarValue 0x4000 77
	JumpIf EQUAL Function#38
	SetVar 0x4000 77
	Message 7
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 28:
	Movement Overworld.2 Action#8
	Movement Player Action#5
	WaitMovement
	Message 19
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 1
	JumpIf DIFFERENT Function#29
	SetVar 0x410E 2
End

Function 29:
End

Function 30:
	Movement Overworld.1 Action#9
	Movement Player Action#7
	WaitMovement
	Message 21
	WaitButton
	CloseMessage
	ReleaseAll
	CompareVarValue 0x410E 2
	JumpIf DIFFERENT Function#31
	SetVar 0x410E 3
End

Function 31:
End

Function 32:
End

Function 33:
End

Function 34:
Jump Function#36

Function 35:
End

Function 36:
	CheckPokegearNumberRegistered 28 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#22
	CheckBadge 15 0x4002
	CompareVarValue 0x4002 1
	JumpIf EQUAL Function#39
Jump Function#22

Function 37:
	CompareVarValue 0x4000 55
	JumpIf DIFFERENT Function#40
	Message 11
Jump Function#41

Function 38:
	Message 8
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#42
	Message 9
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	PartyPokemonTradeScreen
	GetSelectedPartySlot 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#42
	SetVarFromVariable 0x8004 0x800C
	GetPartyPokemonID 0x8004 0x4003
	CheckPartyPokemonForm 0x8004 0x4004
	CompareVarValue 0x4003 0
	JumpIf EQUAL Function#43
	CompareVarValue 0x4004 0
	JumpIf EQUAL Function#44
	CompareVarValue 0x4003 487
	JumpIf EQUAL Function#45
	CompareVarValue 0x4003 492
	JumpIf EQUAL Function#45
	CompareVarValue 0x4003 172
	JumpIf EQUAL Function#45
	CompareVarValue 0x4003 479
	JumpIf EQUAL Function#45
	TextPokeNickname 1 0x8004
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#42
	CloseMessage
	InitTrade 5
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 358
	SetVar 0x4000 55
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 39:
	GetDayOfWeek 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#46
Jump Function#47

Function 40:
	Message 12
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 41:
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 42:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 43:
	TextPlayerName 0
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 44:
	TextPokeNickname 1 0x8004
	Message 13
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#42
	CloseMessage
	InitTrade 5
	TradePokemonScreen 0x8004
	EndTrade
	SetFlag 358
	SetVar 0x4000 55
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 45:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 46:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#48
Jump Function#47

Function 47:
	GetHour 0x4000
	CompareVarValue 0x4000 14
	JumpIf DIFFERENT Function#49
	SetFlag 473
Jump Function#50

Function 48:
Jump Function#22

Function 49:
	CompareVarValue 0x4000 15
	JumpIf DIFFERENT Function#51
	SetFlag 473
Jump Function#50

Function 50:
End

Function 51:
	CompareVarValue 0x4000 16
	JumpIf DIFFERENT Function#52
	SetFlag 473
Jump Function#50

Function 52:
Jump Function#22

//===== ACTIONS =====//
Action 1:
	EmoteExclamation 0x1
End

Action 2:
	WalkEast8 0x1
End

Action 3:
	WalkWest8 0x3
End

Action 4:
	WalkEast8 0x2
End

Action 5:
	WalkOnSpotWest8 0x1
End

Action 6:
	WalkWest8 0x2
End

Action 7:
	WalkOnSpotEast8 0x1
End

Action 8:
	WalkEast8 0x3
End

Action 9:
	WalkWest8 0x1
End

