/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0923
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End

Script 2:
	MecScript
	LockAll
	LockFollowingPoke 0
	WaitFollowingPoke
	SetFollowingPokeMovement 55
	Movement Overworld.4 Action#1
	Movement Player Action#2
	WaitMovement
	WaitFollowingPoke
	LockFollowingPoke 1
	SetFollowingPokeMovement 48
	TextPlayerName 0
	Message 0
	Message 1
	CloseMessage
	Movement Overworld.4 Action#3
	Movement Player Action#4
	WaitMovement
	RemoveOW Overworld.4
	SetFlag 453
	ClearFlag 574
	SetFlag 2422
	SetVar 0x410D 1
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 6:
	LockAll
	CheckFlag 2120
	JumpIf EQUAL Function#1
	SetFlag 2120
	FacePlayer
	Message 5
	Message 6
	PlayCry SPECIES_PLUSLE 0
	WaitCry
	Message 7
	MultiLocalText 1 1 0 0 0x800C
	AddMultiOption 8 0
	AddMultiOption 9 1
	ShowMulti
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 10
Jump Function#3

Script 7:
	LockAll
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 8:
	LockAll
	CheckFlag 2120
	JumpIf EQUAL Function#4
	Message 36
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 9:
	LockAll
	CheckFlag 2120
	JumpIf EQUAL Function#5
	Message 34
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 13
	YesNoBox 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#6
	Message 37
	WaitButton
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8008
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8008 255
	JumpIf EQUAL Function#6
	Message 14
	MultiLocalText 1 1 0 0 0x800C
	AddMultiOption 16 0
	AddMultiOption 17 1
	AddMultiOption 18 2
	AddMultiOption 19 3
	AddMultiOption 20 4
	AddMultiOption 21 5
	AddMultiOption 22 6
	ShowMulti
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#7
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#8
	CompareVarValue 0x800C 2
	JumpIf EQUAL Function#9
	CompareVarValue 0x800C 3
	JumpIf EQUAL Function#10
	CompareVarValue 0x800C 4
	JumpIf EQUAL Function#11
	CompareVarValue 0x800C 5
	JumpIf EQUAL Function#12
	Message 29
	Message 31
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 6
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
Jump Function#6

Function 2:
	Message 11
Jump Function#3

Function 3:
	Message 12
Jump Function#1

Function 4:
	Message 6
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 35
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	Message 23
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 0
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	Message 24
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 1
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 9:
	Message 25
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 2
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	Message 26
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 3
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 11:
	Message 27
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 4
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 12:
	Message 28
	Message 30
	FadeScreen 6 1 0 0
	WaitFadeScreen
	DummyTextTrap 1 5
	FadeScreen 6 1 1 0
	WaitFadeScreen
	Message 32
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
Action 1:
	WalkSouth8 0x4
	WalkEast8 0x6
	WalkNorth8 0x2
	Delay4 0xC
	FaceSouth 0x1
	Delay4 0x4
End

Action 2:
	Delay4 0x14
	WalkNorth8 0x4
End

Action 3:
	WalkEast8 0x1
	WalkSouth8 0x4
	WalkWest8 0x1
	WalkSouth8 0x2
End

Action 4:
	Delay4 0x6
	FaceSouth 0x1
End

