/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0932
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf GREATER/EQUAL Function#1
	CheckBadge 6 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	TrainerBattle TRAINER_PRYCE_032 TRAINER_NONE 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	SetTrainerFlag TRAINER_DEANDRE_482
	SetTrainerFlag TRAINER_GERARDO_484
	SetTrainerFlag TRAINER_JILL_481
	SetTrainerFlag TRAINER_DIANA_480
	SetTrainerFlag TRAINER_PATTON_483
	Message 1
	GiveBadge 6
	AddTrainerScore 22
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#4
	SetVar 0x4077 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
	SetVar 0x8004 334
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	SetFlag 210
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#7
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	CheckFlag 393
	JumpIf LESS Function#8
	ClearFlag 393
End

//===== FUNCTIONS =====//
Function 1:
	CheckBadge 6 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 0
	CloseMessage
	AdrsValueSet 0x20436D4 17
	FlashAnimation
	AdrsValueSet 0x20436D4 0
	TrainerBattle TRAINER_PRYCE_716 TRAINER_PRYCE_716 0 0
	CheckBattleIsLost 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	SetTrainerFlag TRAINER_DEANDRE_482
	SetTrainerFlag TRAINER_GERARDO_484
	SetTrainerFlag TRAINER_JILL_481
	SetTrainerFlag TRAINER_DIANA_480
	SetTrainerFlag TRAINER_PATTON_483
	Message 1
	GiveBadge 6
	AddTrainerScore 22
	CompareVarValue 0x4134 3
	JumpIf DIFFERENT Function#4
	SetVar 0x4077 1
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
	SetVar 0x8004 334
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	SetFlag 210
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#7
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	CheckFlag 2404
	JumpIf EQUAL Function#9
	Message 5
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 3:
	LostBattle
	ReleaseAll
End

Function 4:
	TextPlayerName 0
	Message 2
	PlaySound SEQ_ME_BADGE
	WaitSound
	Message 3
	SetVar 0x8004 334
	SetVar 0x8005 1
	CheckItemSpace 0x8004 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	CommonScript 2033
	SetFlag 210
	CountBadges 0x800C
	CompareVarValue 0x800C 8
	JumpIf EQUAL Function#6
	CompareVarValue 0x800C 7
	JumpIf LESS/EQUAL Function#7
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	CommonScript 2009
	CloseMessage
	ReleaseAll
End

Function 6:
	IncrementVar 0x416F 15
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 7:
	IncrementVar 0x416F 10
	Message 4
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CheckPokeGearRematch 39 0x4001
	CompareVarValue 0x4001 0
	JumpIf DIFFERENT Function#10
	CheckFlag 2404
	JumpIf LESS Function#11
	CheckPokegearNumberRegistered 39 0x4001
	CompareVarValue 0x4001 1
	JumpIf EQUAL Function#11
	GetHour 0x4000
	CompareVarValue 0x4000 6
	JumpIf DIFFERENT Function#12
	SetFlag 750
Jump Function#13

Function 9:
	Message 6
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#14
	CheckAlbumPhoto 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#15
	Message 7
	CloseMessage
	SetFlag 393
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TakePhoto 40
	FacePlayer
	LockAll
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ClearFlag 393
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 10:
	SetFlag 750
End

Function 11:
	ClearFlag 750
End

Function 12:
	CompareVarValue 0x4000 7
	JumpIf DIFFERENT Function#16
	SetFlag 750
Jump Function#13

Function 13:
End

Function 14:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 15:
	Message 10
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	CompareVarValue 0x4000 8
	JumpIf DIFFERENT Function#17
	SetFlag 750
Jump Function#13

Function 17:
	CompareVarValue 0x4000 9
	JumpIf DIFFERENT Function#18
	SetFlag 750
Jump Function#13

Function 18:
	ClearFlag 750
End

//===== ACTIONS =====//
