/*
 * DSPRE Script File
 * Rom ID: test
 * Game: HGSS
 * File: 0948
 * Generated: 9/2/2026 12:10:09 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 1
	JumpIf EQUAL Function#1
	Message 0
	SetFlag 1
Jump Function#1

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 350
	JumpIf LESS Function#2
	GiveItem ITEM_HEART_SCALE 1 0x800C
	CheckItem ITEM_HEART_SCALE 1 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#3
	Message 10
	Message 12
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8005
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8005 255
	JumpIf EQUAL Function#3
	GetPartyPokemonID 0x8005 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#4
	CheckHasLearnableMoves 0x800C 0x8005
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#5
	Message 13
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	RememberMoveScreen 0x8005
	ResponseTeachMove 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#3
	TakeItem ITEM_HEART_SCALE 1 0x800C
	TextPlayerName 3
	Message 25
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 390
	JumpIf EQUAL Function#6
	SetFlag 390
	Message 26
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
Jump Function#8

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 391
	JumpIf EQUAL Function#9
	SetFlag 391
	Message 43
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
Jump Function#11

Script 5:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 61
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#12
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#13
End

Function 2:
	Message 9
	WaitButton
	CloseMessage
	ReleaseAll
	SetFlag 350
End

Function 3:
	Message 11
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 4:
	Message 15
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 5:
	Message 14
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 6:
	Message 27
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#7
Jump Function#14

Function 7:
	Message 28
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 8:
	CheckFlag 210
	JumpIf DIFFERENT Function#15
Jump Function#14

Function 9:
	Message 44
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#10
Jump Function#11

Function 10:
	Message 45
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8000
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8000 255
	JumpIf EQUAL Function#11
	GetPartyPokemonID 0x8000 0x8001
	CompareVarValue 0x8001 0
	JumpIf EQUAL Function#16
	Call Function#17
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#18
	SetVarFromVariable 0x8002 0x800C
	Call Function#19
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#20
	GetPokemonHappiness 0x800C 0x8000
	CompareVarValue 0x800C 255
	JumpIf LESS Function#21
	TextPartyPokemon 0 0x8000
	CompareVarValue 0x8002 1
	JumpIf EQUAL Function#22
	CompareVarValue 0x8002 2
	JumpIf EQUAL Function#23
Jump Function#24

Function 11:
	Message 46
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 12:
	Message 2
	CloseMessage
Jump Function#25

Function 13:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 14:
	GetPartyCount 0x4000
	DecrementVar 0x4000 1
	GetPartyPokemonID 0x4000 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	GetPartyPokemonTypes 0x8004 0x8005 0x4000
	CompareVarValue 0x8004 16
	JumpIf EQUAL Function#27
	CompareVarValue 0x8005 16
	JumpIf EQUAL Function#27
Jump Function#26

Function 15:
	CloseTouchScreen
	Message 63
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 16:
	Message 49
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 17:
	CompareVarValue 0x8001 6
	JumpIf EQUAL Function#28
	CompareVarValue 0x8001 157
	JumpIf EQUAL Function#28
	CompareVarValue 0x8001 257
	JumpIf EQUAL Function#28
	CompareVarValue 0x8001 392
	JumpIf EQUAL Function#28
	CompareVarValue 0x8001 9
	JumpIf EQUAL Function#29
	CompareVarValue 0x8001 160
	JumpIf EQUAL Function#29
	CompareVarValue 0x8001 260
	JumpIf EQUAL Function#29
	CompareVarValue 0x8001 395
	JumpIf EQUAL Function#29
	CompareVarValue 0x8001 3
	JumpIf EQUAL Function#30
	CompareVarValue 0x8001 154
	JumpIf EQUAL Function#30
	CompareVarValue 0x8001 254
	JumpIf EQUAL Function#30
	CompareVarValue 0x8001 389
	JumpIf EQUAL Function#30
	SetVar 0x800C 0
Return

Function 18:
	Message 48
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 19:
	CompareVarValue 0x8002 1
	JumpIf EQUAL Function#31
	CompareVarValue 0x8002 2
	JumpIf EQUAL Function#32
Jump Function#33

Function 20:
	Message 51
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 21:
	Message 50
	WaitButton
	CloseMessage
	CloseTouchScreen
	ReleaseAll
End

Function 22:
	Message 52
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	SetVar 0x8003 307
Jump Function#34

Function 23:
	Message 53
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	SetVar 0x8003 308
Jump Function#34

Function 24:
	Message 54
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#11
	SetVar 0x8003 338
Jump Function#34

Function 25:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8002
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8002 255
	JumpIf EQUAL Function#13
	GetPartyPokemonID 0x8002 0x8001
	CompareVarValue 0x8001 0
	JumpIf EQUAL Function#35
	GetMoveCount 0x800C 0x8002
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#36
	Message 6
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	CMD_394 0x8002
	CMD_395 0x8001
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8001 255
	JumpIf EQUAL Function#12
	TextPartyPokemonMove 0 0x8002 0x8001
	Message 7
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#37
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#12
End

Function 26:
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#38
Jump Function#39

Function 27:
	CheckPokemonHasMove 0x800C MOVE_DRACO_METEOR 0x4000
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#40
	CompareVarValue 0x4000 0
	JumpIf DIFFERENT Function#38
Jump Function#39

Function 28:
	SetVar 0x800C 1
Return

Function 29:
	SetVar 0x800C 2
Return

Function 30:
	SetVar 0x800C 3
Return

Function 31:
	CheckPokemonHasMove 0x800C MOVE_BLAST_BURN 0x8000
Return

Function 32:
	CheckPokemonHasMove 0x800C MOVE_HYDRO_CANNON 0x8000
Return

Function 33:
	CheckPokemonHasMove 0x800C MOVE_FRENZY_PLANT 0x8000
Return

Function 34:
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TeachMovesScreen 0x8000 0x8003
	ResponseTeachMove 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#11
	CloseTouchScreen
	ReleaseAll
End

Function 35:
	Message 5
	CloseMessage
Jump Function#25

Function 36:
	Message 4
	CloseMessage
Jump Function#25

Function 37:
	DeleteMove 0x8002 0x8001
	PlaySound SEQ_ME_WASURE
	WaitSound
	Message 8
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 38:
	DecrementVar 0x4000 1
	GetPartyPokemonID 0x4000 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#26
	GetPartyPokemonTypes 0x8004 0x8005 0x4000
	CompareVarValue 0x8004 16
	JumpIf EQUAL Function#27
	CompareVarValue 0x8005 16
	JumpIf EQUAL Function#27
Jump Function#26

Function 39:
	Message 29
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 40:
	Message 30
	CloseMessage
	FadeScreen 6 1 0 0
	WaitFadeScreen
	ChoosePokemonSelection
	GetSelectedPartySlot 0x8000
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x8000 255
	JumpIf EQUAL Function#7
	GetPartyPokemonID 0x8000 0x8001
	CompareVarValue 0x8001 0
	JumpIf EQUAL Function#41
	Call Function#42
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#43
	CheckPokemonHasMove 0x800C MOVE_DRACO_METEOR 0x8000
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#44
	GetPokemonHappiness 0x800C 0x8000
	CompareVarValue 0x800C 255
	JumpIf LESS Function#45
	TextPartyPokemon 0 0x8000
	Message 62
	CloseMessage
	SetVar 0x8003 434
Jump Function#46

Function 41:
	Message 33
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 42:
	GetPartyPokemonTypes 0x8004 0x8005 0x8000
	CompareVarValue 0x8004 16
	JumpIf EQUAL Function#47
	CompareVarValue 0x8005 16
	JumpIf EQUAL Function#47
	SetVar 0x800C 0
Return

Function 43:
	Message 32
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 44:
	TextMove 0 MOVE_DRACO_METEOR
	Message 34
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 45:
	Message 31
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 46:
	FadeScreen 6 1 0 0
	WaitFadeScreen
	TeachMovesScreen 0x8000 434
	ResponseTeachMove 0x800C
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	CompareVarValue 0x800C 255
	JumpIf EQUAL Function#7
	Message 42
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 47:
	SetVar 0x800C 1
Return

//===== ACTIONS =====//
